### ISSUE TITLE
Proposal to keep gist:hasStandardUnit from a UnitGroup to its standard unit

### ISSUE THREAD

**Issue by rjyounes** [semanticarts/gist#1066]
This is an option in the new units and magnitudes model.

**Comment by uscholdm** [comment]
At the moment it is impossible to know what the standard unit is for a unit group. It has to have a conversion of 1, but more than one unit can have that. E.g. henry per ohm and second are in the duration unit group each with conversion of 1.

**Comment by rjyounes** [comment]
Phil: What's most standard is a representation that's not a unit in QUDT. Don't see benefit.

Michael: Want to know what the standard unit is.

Phil: It's in the dataset for human consumption. Machine-readable, mathematical definition is in the exponents. Also converted to human text in the dataset with each unit.

**Comment by rjyounes** [comment]
Will address when we look at the reference data.

**Comment by uscholdm** [comment]
@philblackwood 
Regarding the role of exponents and standard units. Say the unit group for duration has second and millisecond in it. The exponents are attached to the unit group, and they apply to every unit in the group. So I don't see how the exponents can tell me that the standard unit is second and not millisecond. The difference between second and millisecond is the conversion factor 1 vs. .001. The distinguishing fact about a standard unit is that it has a conversion factor of 1.

**Comment by philblackwood** [comment]
What's missing in the proposal to have a property for hasStandardUnit is a reason.

What I believe is necessary is a way to relate a unit to the base units of SI. This is done two different ways in the reference data.

1. Every unit should be a member of a UnitGroup, and the UnitGroup identifies the exponents of base units that are applicable to all units in the group. For example, if exponentOfSecond is 1 and all the others are zero it means every unit in the group is some multiple of the base unit second (to the first power).
2. Since many people may find it difficult to work with the exponents, every unit has an explicit definition in terms of base units, for example:   1 millisecond = .001 x second   In this representation, the representation includes not only the "standard unit" of second but also the conversion factor. It actually provides more information than just saying a millisecond is somehow related to a second.

The second representation is redundant with other data, but is there for human understanding and could make some human manual calculations simpler.

Adding hasStandardUnit would provide yet another redundant set of data to maintain, with less information content than the equations.

So if the goal is to relate every unit to the base units of SI, that is already done in the reference data (without hasStandardUnit).

If there is a different objective, let's discuss. But if the objective is to be able to relate every unit of measure to the base units then we don't need to include this solution.

**Comment by uscholdm** [comment]
> What I believe is necessary is a way to relate a unit to the base units of SI. 

Agreed

> 
> 1. Every unit should be a member of a UnitGroup, and the UnitGroup identifies the exponents of base units that are applicable to all units in the group. For example, if exponentOfSecond is 1 and all the others are zero it means every unit in the group is some multiple of the base unit second (to the first power).

Yes, however the current representation does not distinguish base units from other units. 

> 2. Since many people may find it difficult to work with the exponents, every unit has an explicit definition in terms of base units, for example:   1 millisecond = .001 x second   In this representation, the representation includes not only the "standard unit" of second but also the conversion factor. It actually provides more information than just saying a millisecond is somehow related to a second.

This is useful text for the human.  It's a good idea to have this. 
- `1 millisecond = .001 x second` makes perfect sense, as does 
- `1 second = 1.0 x second`.  However there are odd examples such as 
- `1 square meter = 1.0 x meterSquared` 
There are two text variants referring to the same thing. This does not make sense.

> 
> The second representation is redundant with other data, but is there for human understanding and could make some human manual calculations simpler.

Agreed

> Adding hasStandardUnit would provide yet another redundant set of data to maintain, with less information content than the equations.

Redundancy usually has a maintenance cost, but it does not arise here. Unit information is entered once and stays put.

ALSO: I noticed that each `UnitGroup` has a `scopeNote` indicating the standard unit as text. For example
- `gistd:_UnitGroup_duration skos:scopeNote "second"`
- `gistd:_UnitGroup_area skos:scopeNote "meterSquared"`
This could be replaced by `gist:hasStandardUnit` and point to the IRI of the unit itself. No extra triples. Nothing to maintain. Specifically, 
- `gistd:_UnitGroup_duration skos:scopeNote gist:_UnitOfMeasure_second`
- `gistd:_UnitGroup_area skos:scopeNote gistd:_UnitOfMeasure_square_meter`
> 
> So if the goal is to relate every unit to the base units of SI, that is already done in the reference data (without hasStandardUnit).
> 
> If there is a different objective, let's discuss. But if the objective is to be able to relate every unit of measure to the base units then we don't need to include this solution.

My goal is to be able to easily click around the definitions (in say AllegroGraph) and find out what the IRI for the standard unit is for a given UnitGroup, that seems to be not possible now.

**Comment by philblackwood** [comment]
We discussed this during reviews and the consensus seems to be to not include it. 

For completeness of the discussion, here is what the International System of Units says about it:

"Derived units are defined as products of powers of base units. When the numerical factor of this product is one, the derived units are called coherent derived units. The base and coherent derived units of the SI form a coherent set, designated the set of coherent SI units. The word "coherent" here means that equations between the numerical values of quantities take exactly the same form as the equations between the quantities themselves."

**Comment by uscholdm** [comment]
@philblackwood Yes, the decision was to not keep standard units. The quote about coherent units is interesting, im glad you included it. It mentions 3 fundamental things that no longer have any overt existence in gist.
1. base unit
2. derived unit
3. coherent derived unit

I support the idea of having a scope note on unit of measure to briefly explain the logic of not including these.
