### ISSUE TITLE
Language should be a subclass of Artifact

### ISSUE THREAD

**Issue by rjyounes** [semanticarts/gist#1126]

**Comment by uscholdm** [comment]
Maybe whales have a language? Broaden Artifact definition to be 'mammal-made'?

**Comment by rjyounes** [comment]
Not sure if this is tongue in cheek, but I guess you're right, animals can have languages, and not just mammals. No, I don't think we want to broaden artifact to mean mammal made or animal made. However, perhaps it should include computer-made objects. I don't think in our current world we can infer from the fact that a computer is human-made, and X is computer-made, that X is human-made.

**Comment by stevenchalem** [comment]
Until there are language tags for non-human languages, I think it's safe to treat "Language" as synonymous with "human language." Gist is already English-centric; keeping it anthropocentric should be acceptable.

**Comment by stevenchalem** [comment]
But we wouldn't want to expand "Artifact" to include creations of non-human agents, since that goes against the common usage of the word. Instead, Artifact could be a sub-class of BiogenicThing, which would encompass the products of animals, plants, bacteria, etc. TechogenicThing could cover the products of computers, robots, etc. Finally we could have a superclass for BiogenicThing and Technogenic thing. But let's wait until we have some client use cases.

**Comment by rjyounes** [comment]
> Until there are language tags for non-human languages, I think it's safe to treat "Language" as synonymous with "human language." Gist is already English-centric; keeping it anthropocentric should be acceptable.

The current gist definition of Language already includes computer languages.

**Comment by stevenchalem** [comment]
> The current gist definition of Language already includes computer languages.
For now, at least, those are still artifacts.
