### ISSUE TITLE
Fix definition of hasJurisdiction 

### ISSUE THREAD

**Issue by rjyounes** [semanticarts/gist#148]
"when laws and contracts are meeted out"

1. Definition seems wrong altogether
2. "meted" not "meeted"

**Comment by rjyounes** [comment]
Dictionary definitions of "jurisdiction":

Google:
"The official power to make legal decisions and judgements."

Merriam-Webster:
"The power, right, or authority to interpret and apply the law."
"the authority of a sovereign power to govern or legislate"
"the power or right to exercise authority"
"the limits or territory within which authority may be exercised"

Cambridge:
"the official authority to make (esp. legal) decisions and judgments"

Wikipedia:
"the practical authority granted to a legal body to administer justice within a defined field of responsibility...Colloquially it is used to refer to the geographical area to which such authority applies, e.g. the court has jurisdiction over all of Colorado. The legal term refers only to the granted authority, not to a geographical area."

**Comment by rjyounes** [comment]
Recommendation:

skos:definition: "The legal body has been granted the practical authority to administer justice within a defined field of responsibility."
skos:scopeNote: "While colloquially 'jurisdiction' is used to refer to the geographical area to which such authority applies, e.g. the court has jurisdiction over all of Colorado. The legal term refers only to the granted authority, not to a geographical area."

**Comment by rjyounes** [comment]
I also recommend the property name be changed to hasJurisdictionOver, since hasJurisdiction does not imply the existence of an object.

**Comment by uscholdm** [comment]
It turns out the concept of jurisdiction is multifaceted.  In 2010, Dave and I read a 20-page paper describing this, authored by Lexis Nexis. Jurisdiction can be over a region, but also a subject. A police department has jurisdicion over drugs but not prostitution, say.  Id be careful about restictiong the domain or range.

**Comment by rjyounes** [comment]
Agree completely.

**Comment by marksem** [comment]
+1

I agree the definition should change, and I'm good with the local name change as well.

**Comment by rjyounes** [comment]
@uscholdm There's no domain or range stated - though possibly we could define an appropriate domain. If you're referring to my proposed scope note, that can be reworded:

"While colloquially 'jurisdiction' is sometimes used in relation to geographic areas, such as jurisdiction over the State of Colorado, legal jurisdiction pertains to the administrative area rather than the geographic one."

- The United States District Court for the Eastern District of New York has federal jurisdiction over the counties of Kings, Nassau, Queens, Richmond, and Suffolk.
- The FDA Office of Criminal Investigations has jurisdiction over the Federal Food, Drug, and Cosmetic Act (FDCA) and the Federal Anti-Tampering Act (FATA).

**Comment by uscholdm** [comment]
It seems there are three things going on.
1. who has the power, authority or is responsible. Normally it would be a legal body, but not necessarily. Also, I could imagine a person rather than an organization having the authority. 
2. what is authorized -- typically the right to enforce laws and administer justice, but maybe the right to make policies or regulations.  There could be a number of things.
3. the context in which the authority holds.  Often a geographic region. Could be a particular law or a general topic for which many laws apply (e.g. illegal drugs).

So maybe Jurisdiction is really a ternary relationship that we want to stuff into a binary property by combining the latter two things?   A binary property would not allow a nice way to capture the commonality between:
- O1 hasJuristiction over LAW 1 in Oregon
- O2 hasJuristiction over LAW 1 in Texas
- O3 hasJuristiction over LAW 2 in Texas

Its not often one comes up with a genuine ternary relation. The only other commercially interesting example I know of is a material having  particular purpose when used in a given product (from P&G). For example: 
- M1 used as a emulsifier in P1
- M2 used as a emulsifier in P2
- M3 used as a solvent in P2

**Comment by rjyounes** [comment]
@uscholdm I like this analysis. The ternary relationship sounds good to me.

**Comment by rjyounes** [comment]
Name changed to `hasJurisdictionOver` in PR #535

**Comment by rjyounes** [comment]
Change definition. Add scopeNote indicating that if users need more complexity they can define a materialized ternary relationship.

**Comment by rjyounes** [comment]
Local name and label changed in gist `10.0.0`. This issue now involves only the definition.

**Comment by rjyounes** [comment]
I've just noticed that the predicate seems to mean the opposite of what I thought, and that therefore the name change to `hasJurisdictionOver` was incorrect. The definition of `Contract` is:

```
gist:Contract
	a owl:Class ;
	owl:equivalentClass [
		a owl:Class ;
		owl:intersectionOf (
			gist:Agreement
			[
				a owl:Restriction ;
				owl:onProperty gist:hasJurisdictionOver ;
				owl:someValuesFrom gist:GovernmentOrganization ;
			]
		) ;
	] ;
.
```
Changing `hasJurisdiction` to `hasJurisdictionOver` implies the opposite, and wrong, meaning.  New issue #637 created for the bug fix.

**Comment by rjyounes** [comment]
Covered in #640
