### ISSUE TITLE
Review GeoRegion proposal from Ted and decide on implementation path

### ISSUE THREAD

**Issue by rjyounes** [semanticarts/gist#151]
@uscholdm Can you please attach any documents that you have on this to the issue?

**Comment by tedhills** [comment]
[GeoConceptsPart1-2019-10-03-post.pptx](https://github.com/semanticarts/gist/files/4575871/GeoConceptsPart1-2019-10-03-post.pptx)
[GeoConceptsPart2-2019-10-03.pptx](https://github.com/semanticarts/gist/files/4575874/GeoConceptsPart2-2019-10-03.pptx)
[GeoConceptsPart3-2019-11-08.pptx](https://github.com/semanticarts/gist/files/4575876/GeoConceptsPart3-2019-11-08.pptx)

**Comment by tedhills** [comment]
I've uploaded all three PowerPoint decks covering our discussions of this issue. It's important to note that the third deck changes some of the statements in the first two decks.

Resolution of this issue depends on issue #152 , because a :GeoPoliticalEntity must have two parts (region and government), and we need to know what object property we will use to express the part/whole relationship.

**Comment by uscholdm** [comment]
@rjyounes 
DECISION: has been addressed elsewhere and included in release 11.0.0. See [#215](https://github.com/semanticarts/gist/issues/215) and [#183](https://github.com/semanticarts/gist/issues/183)

NOTE: thanks to @tedhills Ted for a spectacular amount of effort that helped us move forward in addressing a number of geo issues.
