### ISSUE TITLE
Several object properties are lacking definitions and labels

### ISSUE THREAD

**Issue by tedhills** [semanticarts/gist#16]
Most object properties are missing labels in gist 7.5, In addition, the following object properties are missing definitions in gist 7.5:

gist:affectedBy
gist:allows
gist:aspectOf
gist:communicationAddressof
gist:describedIn
gist:directPartOf
gist:directSubTaskof
gist:expressedIn
gist:fromPlace
gist:geoContainedIn
gist:geoDirectlyContainedIn
gist:geoOccupiedBy
gist:geoOccupies
gist:permanentGeoOccupies
gist:governedBy
. . .
the list is incomplete

**Comment by mkumba** [comment]
with version number fixed in

gist:affectedBy 8
gist:allows  8
gist:aspectOf  8
gist:communicationAddressof 8
gist:describedIn 8
gist:directPartOf 8
gist:directSubTaskof 8
gist:expressedIn 8
gist:fromPlace 8
gist:geoContainedIn 8
gist:geoDirectlyContainedIn 8
gist:geoOccupiedBy 8
gist:geoOccupies 8
gist:permanentGeoOccupies 8
gist:governedBy 8
