### ISSUE TITLE
Use skos:definition, skos:prefLabel

### ISSUE THREAD

**Issue by tedhills** [semanticarts/gist#17]
There's a strong suggestion that skos:Definition be used instead of rdfs:Comment to hold definitions. This would allow rdfs:Comment to be used for additional, non-definitional commentary.

There is a strong suggestion that skos:prefLabel be used instead of rdfs:label.

**Comment by rjyounes** [comment]
skos:definition is preferable for definitions due to its specificity; rdfs:comment is just that, a comment providing additional information but not necessarily a definition. 

I also suggest using skos:example for examples; I typically put only a single example in each skos:example assertion, but don't have strong feelings about that approach vs combining multiple examples into a single assertion.

rdfs:label is commonly used for labels in ontologies and I would stick with that; as suggested above, many tools are reliant on it. I use skos:prefLabel in taxonomies. Are there any ontology tools - as opposed to taxonomy tools - that expect a skos:prefLabel? I suspect not but am not certain.

I advise against doubling due to the inevitable maintenance problems created by redundancy.

**Comment by rjyounes** [comment]
Duplicate of #85.

See also proposal for use of annotation properties at https://semarts.atlassian.net/wiki/spaces/AD/pages/774242422/Action+Item+05+Standard+Conventions+for+Ontologies+and+Taxonomies (SA internal only).
