### ISSUE TITLE
Inline documentation

### ISSUE THREAD

**Issue by pwin** [semanticarts/gist#196]
I think the deliverable would benefit from a decent level of inline documentation on all elements of the ontology , and perhaps this means that there is a documentation-rich and a doc-light version of the bundle

**Comment by Jamie-SA** [comment]
I've been thinking about adding additional content, even media rich content such as links to the gist Council recordings or Slow Reveal presentations. It seems these aren't really part of the Ontology so I've wondered if maybe this type of annotation should go into a separate file that is available as part of the download.
It would be available to a UI built for exploring an Ontology.

**Comment by rjyounes** [comment]
I agree that it should not be part of the ontology but as a separate file.

**Comment by pwin** [comment]
Perhaps it could be an optional import. We'd want it to be RDF, wouldn't we?

Alternatively, it could be RDFa in HTML

**Comment by Jamie-SA** [comment]
Yes, I am assuming there would be an RDF that can includes various other kinds of information about the ontology. Some of data may link to media that is not RDF, such as a YouTube video, images, documents, etc.

**Comment by rjyounes** [comment]
If it's RDF in the gist namespace it is part of the ontology whether or not it lives in a separate file. IMO this is documentation, not part of the ontology.

**Comment by Jamie-SA** [comment]
I don't remember that definition of ontology from any of the specifications. IIRC, an ontology is the terms included in the import closure (I think that is the right term, I didn't look it up) over the set of ontology documents.
Namespaces, I think, are more of a human convenience.
I'd be interested in @pwin 's take on this since he often has a little different perspective.

Then there is *can* and there is *should*.

**Comment by rjyounes** [comment]
Let's say in one file you have:

```
gist:someClass a owl:Class .
```

And in another file you have:

```
gist:someClass rdfs:seeAlso :someResource .
```
When you dump all of those into a triple store, then the rdfs:seeAlso assertion is part of the ontology.

**Comment by Jamie-SA** [comment]
I disagree. IIRC, the OWL specification of an ontology does not talk about what happens in a triplestore. The specification only deals with ontology documents.

The cool part of RDF is you can say anything you want about anything. But to do so you use the URI of the term (gist:someClass). That doesn't "add" it to the ontology. If I want to add some annotation to foaf terms in my triplestore, I should be able to do that. That doesn't change the foaf ontology.

**Comment by rjyounes** [comment]
It's true that in RDF you can say anything about anything, but in universe of Linked Open Data "in the wild" things are more complicated than in a private triple store.

If you make an assertion about a URI that you don't own - I.,e in a domain you don't own - that assertion will never be returned when someone dereferences the URI, since only the URI owner has control over that. Thus, it would not only be "bad" to say something about a foaf term, it's not possible to do so in any meaningful way. In your own triple store you can of course do anything you want, but that has no bearing on the foaf term as it exists publicly. 

Because I do not think the references you are describing, such as gist council recordings, should be formally linked to our ontology terms, I don't favor the rdfs:seeAlso assertions.

**Comment by uscholdm** [comment]
> Because I do not think the references you are describing, such as gist council recordings, should be formally linked to our ontology terms, I don't favor the rdfs:seeAlso assertions.

I don't agree with this reasoning. I think this is conflating different things.  
1. Is a seeAlso statement useful to have to help document an ontology
1. If so, where is the best place to put it

**Comment by Jamie-SA** [comment]
Referencing a couple comments from @MichaelSullivanArchitect in another issue.
https://github.com/semanticarts/gist/issues/259#issuecomment-629296381
https://github.com/semanticarts/gist/issues/259#issuecomment-629340529

**Comment by Jamie-SA** [comment]
Another goal I have is to start using our (Semantic Arts) ontology presentation technology to explain and show examples of how to use different parts of gist. We need a few more features to make this work and ready for release but we will soon be able to provide presentations of ontology features that we can publish for public consumption.

For any gist term we should be able to list which presentations include the term.

**Comment by MichaelSullivanArchitect** [comment]
You can see how I used such diagrams for a blog I recently posted: [https://www.ateam-oracle.com/knowledge-graph-modeling%3A-introduction-to-gist-and-buckets](url)

**Comment by pwin** [comment]
move documentation issues and discussion to https://github.com/semanticarts/gist-doc
