### ISSUE TITLE
Update all labels according to a standard convention

### ISSUE THREAD

**Issue by uscholdm** [semanticarts/gist#20]
A number of gist resources do not have labels.  They probably should be there, across the board.

**Comment by rjyounes** [comment]
Need to agree on conventions before this is addressed.

**Comment by rjyounes** [comment]
I will make a proposal for the next meeting, but not committing to the implementation.

**Comment by rjyounes** [comment]
Proposal:

My proposal involves mapping from local names to labels, so I begin with my proposed _orthographic_ (as  opposed to structure/content) conventions for local names:

Classes: camelcase, initial uppercase. Acronyms also camel-cased so that word boundaries are unambiguous - e.g., AmaGuideline not AMAGuideline. Alphanumeric characters only - e.g., Isbn10, not Isbn-10 or ISBN-10.

Properties: camelcase, initial lowercase. 

Both: non-standard abbreviations should not be used: e.g., hasUoM should be hasUnitOfMeaure. 

Labels:
Classes: Initial uppercase, remainder lowercase, normalized to natural language standards - I.e., hyphens inserted, acronyms in all caps, etc. Examples: NSDAP officer, ISBN-10. I prefer only initial word capitalized because sentence case, while technically well-defined, can introduce inconsistencies when actually implemented by different people.

Properties: same as classes, with initial lowercase. Hypothetical examples: has unit of measure, has SSN. Initial lowercase follows the convention applied to local names.

These conventions facilitate automated mapping between local names and labels. E.g., "hasUoM" and label "Has Unit of Measure" cannot be automatically mapped to one another. Labels with acronyms and  hyphens can be automatically mapped to local names but not the reverse, but this is a general problem.

**Comment by rjyounes** [comment]
Michael: Separate end of acronym from beginning of word with underscore.

Boris: Likes entire proposal.

Dan: Uppercase label for property names, though lowercase in local names. Capitalization in column names is better. Reference to MS.

Boris: Should in this case argue for alternative labels of some sort. Could create other annotations like hasOfficialName for special-purpose labels. URI and prefLabel should not be driven by display or other concerns. 

Michael: Different clients can decide to do things differently. 

Consensus: adopt this proposal.

**Comment by Jamie-SA** [comment]
A comment regarding automated mapping of terms to labels, it seems that the purpose of a label is the ability to provide something different than what is contained in the name. If it is required that it be possible to automate it then you wouldn't need labels (at least for the English language).

**Comment by rjyounes** [comment]
The idea is it would be different but could be unambiguously mappable to the extent possible. For example, "AMA Guideline" can be automatically mapped, according to the above conventions, to the local name "AmaGuideline" - though not the reverse in all cases. A local name can in theory be completely arbitrary, such as a code, and doesn't really have any meaning per se; it's only by convention that we adopt specific formats for them.  The idea of automation is to reduce human effort in maintaining the labels.

**Comment by rjyounes** [comment]
On further consideration, I don't like the idea of adding application-specific annotations to an ontology, such as for column name display. In my opinion, ontologies should be entirely independent of any tools used with them. An annotation like hasOfficialName is valid because it has semantic content, but an annotation which essentially is valueToDisplayAsSpreadsheetColumnHeader is not. I realize this isn't quite relevant here, but in previous semantic applications I've worked on we used an application ontology or display ontology to control interface features. I think this is what Jamie and team are doing in DCA.

**Comment by uscholdm** [comment]
> it seems that the purpose of a label is the ability to provide something different than what is contained in the name

The goal is readable and convenient labels.   90% of the time, it can be automated from CamelCasing by just inserting spaces.   TopBraid does this for you automatically, and it is over-rideable.

**Comment by uscholdm** [comment]
Application-specific labels could be in separate application-specific annotation ontologies that import the main ontology.

**Comment by rjyounes** [comment]
@uscholdm Yes, this was my thought.

**Comment by rjyounes** [comment]
This issue was originally a combination of adding missing labels and fixing labels and local names based on a defined convention. I'm splitting this into different issues. The issue for adding missing labels is now #153.

Dan will start by creating a list of new local names based on his understanding of the implementation conventions. Others will review before modifying the OWL.

@DanCarey404 Would it make sense for the list to include both local names and labels, so that we don't have a two-step review?

Moved to February 2020 project since no time to get done for January 2020.

**Comment by rjyounes** [comment]
Comment from @DanCarey404 left on issue #153, which also touches on sentence vs title case:

I definitely do not remember agreeing to sentence case for labels.  And a quick search of the notes in #20 show nothing like that.

I, for one, do not like the idea of sentence case labels.  We should resolve this issue quickly.

**Comment by rjyounes** [comment]
@DanCarey404 I am quoting the sections of the discuss/decision where we made this decision:

My original proposal:

```
Labels:
Classes: Initial uppercase, remainder lowercase, normalized to natural language standards - I.e., hyphens inserted, acronyms in all caps, etc. Examples: AMA guideline, ISBN-10. I prefer only initial word capitalized because title case, while technically well-defined, can introduce inconsistencies when actually implemented by different people.

Properties: same as classes, with initial lowercase. Hypothetical examples: has unit of measure, has SSN. Initial lowercase follows the convention applied to local names.
```

Our decision:

```
Adopt entire proposal.
```

I would also point out that, since we agreed on initial lowercase for labels, title case for the remainder would not make sense.

**Comment by rjyounes** [comment]
We should revisit these decisions at the next review meeting if there are concerns. We should not attempt to settle it via email or Team chat.

**Comment by DanCarey404** [comment]
Here are the proposed new names.  I have a separate tab just for the geolocation-related properties, because there are so many variations to choose from.  We can discuss at an upcoming meeting and/or vote via Polly on Teams.
I suppose we ignore the "prefLabel" column pending a confirmed consensus on the format for that.
[gist9PropertiesRenamed.xlsx](https://github.com/semanticarts/gist/files/4118772/gist9PropertiesRenamed.xlsx)

**Comment by rjyounes** [comment]
@DanCarey404 My preference is for all object properties to begin with a verb. However, this issue started as only a discussion of the orthographic convention. It could be argued that if we are going to implement new names, we ought to discuss all related conventions so we don't make two passes, but logically these are separate issues and can be discussed independently. I am going to open a new issue for the wording of local names, and will link the two.

**Comment by uscholdm** [comment]
This is the perfect candidate to use Office 360 collaborative editing feature.

Michael

**Comment by rjyounes** [comment]
gist Issue Review discussion 2020-01-30

Dan: remember agreeing to local names but not labels, in particular sentence case vs title case.

MarkW: no right way, just need a consistent way. Sentence case not preferred, but can live with it. Rationale for title case - column header. On the other hand, sentence case makes more sense for text generation. Will accept previous decision since he wasn't at the meeting.

We'll create a style guide to document decisions so others can reference them during development. The style guide will be built up as we address issues. Include details and examples, but don't include rationale and thinking that went into it.

MarkW: Reference Google's Java coding style guide. They also adopt the acronym proposal.
https://google.github.io/styleguide/javaguide.html

Dan: don't always need examples. 

Rebecca: Rationale for sentence over title case: latter is more complex, not always consistently applied.

Dan: wants to make sure everyone is in agreement with sentence case. Not his preference, but will go along with. 

DECISION: Stick with previous decision.

Dan: ignore pref label column of document he attached. Concentrate on local name. 

Action: we all review Dan's local names for next meeting. Dan will put doc on Office 365 and send email to other ontologists informing them that it's there to comment, we will discuss at Feb 20 meeting. Will delete prefLabel column. Add comment column - put initials on comments.

Dan's proposal also includes verb/noun distinction for object/datatype properties.

**Comment by rjyounes** [comment]
Dave is opposed to do all at once.

Dan has issues with keeping Morgan Stanley in sync.
MarkW doesn't think this is a problem. MS will take cues from new versions but will manually upgrade pieces they want.
Dan: MS already has a problem upgrading to https. Will bring in salient changes. Shouldn't block changes to gist.

Rebecca: One option: keep current terms as is, moving forward use Style Guide.

Dan: there's a subset that we want to propose changing, don't have to do across the board. Let's leave the bulk alone. Offers to handle labels following conventions.

Michael: what would be involved in upgrading PLEO to new gist local names (as an example). Change ontology, sparql, tarql. 
Boris: not too many uses

Jamie: Platts doesn't have much code base built on the ontology. MS is starting to code against the ontology. Code would have to change, not just ontology, queries, and tarql.

Equivalent properties will allow querying with old terms if equivalent property reasoning is turned on.

MarkW: people don't have to move forward. Shouldn't live with these types of errors and inconsistencies. 

Dan: agree with MarkW. This is a signature product, this would enhance the professional quality of the ontology. Likes idea of separate file for deprecated terms (we already have this).

Michael: do thorough round of cleaning and tidying, ignoring URI changes. Next step can be URI changes. Then users can get the cleaned up version without the URI changes.

Jamie: another option: start to target 10. Make immediate changes to 9 (everything minus URI changes). 

Rebecca: if we remove gistWiki, will we deprecate terms or have a major release.
gistWiki was not even updated to https URIs in gist 9. 
Never mind, this will be a patch.

**Decision:** we will leave local names as they are, fix all label contents. Use new convention based on existing local names.

**Comment by rjyounes** [comment]
Latest version of Dan's proposal is attached.
[gist9PropertiesRenamed.xlsx](https://github.com/semanticarts/gist/files/4269410/gist9PropertiesRenamed.xlsx)

**Comment by uscholdm** [comment]
I thought this was on Office 360. If not, it probably should be.

**Comment by rjyounes** [comment]
I disagree. The GitHub issue should be the authoritative source of all information related to the issue; this was one of the purposes of trying to move discussions out of emails and into issues. The goals are transparency (SA Office 365 is not publicly available) and tracking.

**Comment by rjyounes** [comment]
I was hoping we could fully track the discussion in the issue, but you're right that there is no way to co-edit here. For SA ontologists, the document is now on the Semantic Arts One Drive for commenting.

**Comment by rjyounes** [comment]
I've confused the issue. Dan's document pertains to local names, while this issue is now only about labels. I will move the comments to #188.

**Comment by mkumba** [comment]
thanks

Sent from Mail<https://go.microsoft.com/fwlink/?LinkId=550986> for Windows 10

________________________________

**Comment by mkumba** [comment]
Somehow this thread seems to have drifted from changing the labels to changing the actual names (the URIs) of properties.  If both options are still on the table, let's make two issues.

**Comment by rjyounes** [comment]
There are two issues. Labels #20, Local names #188.

**Comment by mkumba** [comment]
thanks

Sent from Mail<https://go.microsoft.com/fwlink/?LinkId=550986> for Windows 10

________________________________

**Comment by sa-bpelakh** [comment]
To make sure we catch it here, `rdfs:label` of `gist:hasIncumbent` is mis-spelled in gistNetwork.

**Comment by rjyounes** [comment]
Replaced by #227.

**Comment by rjyounes** [comment]
Four alternatives:

1. Title case for all
2. Title case for classes; sentence case for properties, starting with lowercase
3. Sentence case all
4. Sentence case all; uppercase classes vs lower case properties

Dave: When do we see labels?
- Graphics
- Forms
Which would you rather see?

Rebecca: we also see them in documentation (e.g., Widoco)

Peter: accuracy more important than typographic consistency

Will vote next meeting.
