### ISSUE TITLE
Create and use a gistx namespace

### ISSUE THREAD

**Issue by uscholdm** [semanticarts/gist#206]
For consistently with what we do with all our clients, I propose that we have the taxonomic individuals in gist use a gistx namespace prefix just like we do with our clients.  I guess the namespace would be:
`httpx://taxonomies.semanticarts.com/gist/`

This would mostly be for units. Not clear what do do with unitedNations.

**Comment by rjyounes** [comment]
I agree. And we could apply the 'd' suffix as we do with clients for data (I.e., gistd).

**Comment by uscholdm** [comment]
My first thought is that, almost by definition, being an upper enterprise ontology, that would be no data in any gistd namespace.  What data were you thinking might go into a gistd namespace?  Perhaps timecard?  If it has its own namespace, we should use that. Or maybe that is where we use gistd.

**Comment by rjyounes** [comment]
You mentioned UnitedNations. If we don't want a data namespace, then we should remove it. It does seem odd to define it in gist.

I agree that timecard should have its own namespace, so I wasn't thinking of that.

There are a number of other individuals defined in gist. Most of them would be deleted if we adopt your proposal in #61; _greenwichTimeZone is an exception. I can imagine _gregorianCalendar and possibly others, though languages and countries we would probably take from an external dataset. You might write a calendar module that would define months of the year, possibly different calendars like gregorian, hijra, etc. Or do you want to say across the board that an upper ontology doesn't define any data, so that that wouldn't belong in gist?

**Comment by uscholdm** [comment]
Maybe we should use an external URI for the UN, there will be dozens to choose from.

Implementing https://github.com/semanticarts/gist/issues/61 will not get rid of the core units, there still needs to be instances for meter, second, kilogram etc.  It would only get rid of a few, but mostly it gets rid of the need to create any more such (redundant) magnitude instances moving forward.

**Comment by rjyounes** [comment]
I wasn't thinking #61 would get rid of the core units, but it would get rid of the durations like _one_millisecond, correct?

Agreed, it would be preferable to use external URIs for common objects like the United Nations. It seems odd that it was ever defined in gist.

So we can forget about gistd for now but remember that if we do start creating data objects we should use it rather than the gist namespace.

I've created #207 to remove _unitedNations.

**Comment by uscholdm** [comment]
> I wasn't thinking #61 would get rid of the core units, but it would get rid of the durations like _one_millisecond, correct?

Yes.

**Comment by rjyounes** [comment]
That's my understanding.

**Comment by rjyounes** [comment]
Duplicates #305
