### ISSUE TITLE
Add gist:Ownable (or gist:Asset) and associated entities

### ISSUE THREAD

**Issue by DanCarey404** [semanticarts/gist#220]
[Ownable.pptx](https://github.com/semanticarts/gist/files/4422179/Ownable.pptx)
gist Council presentation (as presented on 2020-04-02).

**Comment by pwin** [comment]
http://ontology.buffalo.edu/FARBER/hare.html
 
There is reference to ownable incorporating elements of control (i.e. right), intention and time

**Comment by pwin** [comment]
there has been a gist:Ownable before – see Michael’s article-  http://ceur-ws.org/Vol-1586/codes1.pdf which was “EquivalentClass gist:Money or gist:Organization or gist:Permission or gist:PhysicalThing” , so what happened there?

**Comment by pwin** [comment]
[real_estate1.pdf](https://github.com/semanticarts/gist/files/4426244/real_estate1.pdf)
You might have seen it before, but Barry Smith’s paper on real estate is interesting (attached).  Registers of Scotland are doing some ontology on registered property, and this goes deep into ‘title’ – which is something similar to rights, obligations, and prohibitions [e.g. W3C ODRL]. These are burdens of title.  Title is inheritable and can be transferred for a consideration [ https://www.upcounsel.com/legal-def-sale ]

**Comment by uscholdm** [comment]
I think gist:Ownable was removed because it was an abstract class and not clearly useful.  Dave decision 1-3 years ago.

**Comment by pwin** [comment]
So @uscholdm is it now any less abstract and any more useful?

**Comment by pwin** [comment]
The notion of gist:Right as suggested in @DanCarey404  presentation is perhaps not worded as I would - because we talk about 'inalienable rights' - ones that don't require any permission as such to exercise.  However, something like 'title' could cover both in that it is a form of permitted control that is transferable and this can be across generations (inheritable) and also for a consideration (a sale).  It can also be forcibly removed by e.g. law, whereas some forms of 'right' cannot.

**Comment by uscholdm** [comment]
> So @uscholdm is it now any less abstract and any more useful?

I think not, but only Dave made the initial decision. There are lots more cooks now with different ranges of preferred spices. I have not heard Dave indicate he changed his thinking.

**Comment by uscholdm** [comment]
> we talk about 'inalienable rights' - ones that don't require any permission as such to exercis
For our purposes, Rights are matters of law.  So called inalianable rights may be explicitly permitted in a constitution.  Other constitutions may explicitly deny those same rights, which are  hence 'alienable' in that other system of law. So fundamentally, I think for all of our practical purposes we can regard a Right as a Permission.

**Comment by rjyounes** [comment]
Why don't we call it LegalRight to distinguish it from rights defined in a religious context or when speaking of human rights? You may or may not believe that such rights exist, but regardless of that they exist as concepts. Understood that gist is an enterprise ontology, but even if we don't want to model non-legal sorts of rights, we could still name it to be less ambiguous.

Second: I don't agree with defining a right merely as a set of legal permissions. It is also a set of legal **prohibitions** to other people. E.g., if I own a car, not only does that allow me to do certain things to it, it also legally prohibits other people from, say, driving it without my permission or destroying it.

**Comment by pwin** [comment]
There is a profile of ODRL that covers these burdens and prohibitions, and
I think waived rights too -
https://ai.wu.ac.at/policies/orcp/regulatory-model.html

**Comment by uscholdm** [comment]
We both agree that the permission to do something is very different from a prohibition from doing something. That is why we have gist:Permission and gist:Restriction.   Rebecca seems to be suggesting that gist:Right is a subclass of the union of gist:Permission and gist:Restriction. I think it confuses things to conflate right with prohibition.

**Comment by rjyounes** [comment]
When we say I have the right to life, liberty, and the pursuit of happiness, doesn't this include things that other people cannot do to me, as well as things I can do?

**Comment by rjyounes** [comment]
And @uschold I think this suggests not that Right is a subclass of both Permission and Restriction, but that it _includes_ permissions and restrictions.

**Comment by rjyounes** [comment]
Or should we go the other way and say that what is termed the "right" to the pursuit of happiness in common parlance is not really a single thing, but a collection of permissions (rights) and prohibitions?

**Comment by uscholdm** [comment]
> When we say I have the right(s) to life, liberty, and the pursuit of happiness, doesn't each of these three rights include things that other people cannot do to me, as well as things I can do?

> Or should we go the other way and say that what is termed the "right" to the pursuit of happiness in common parlance is not really a single thing, but a collection of permissions (rights) and prohibitions?

A right is (most?) often a right do DO something. A right to HAVE something (e.g. liberty) is different,  and that is where there are implicit prohibitions.  You might also have the right to BE something (e.g. happy) or to BELIEVE something (that pi is an irrational number).

The idea of permission is mostly about to DO, less so about to HAVE, BE or BELIEVE.

**Comment by rjyounes** [comment]
Dave: Ownership is the right to destroy something.

Dan: Consider `Asset` rather than `Ownable`.

Rebecca: Remove `Permission` as subclass?

Rebecca: Can own a copyright. 

Jamie: In accounting, intangible assets like good will.

Dan: Part of it is the ability to give it away.

Jess: `ownedBy` property. 

Dan/Jamie: `Asset` and `Ownable` not equivalent.

Dan: Good will is an asset but not ownable.

Jamie: Good will is a business concept to account for value of intangible assets. E.g., if you sell a business or part of a business with a well-known brand, the brand can add to the value; this is good will.

Dave: Asset is something that's owned and has a monetary value. 

Rebecca: So Ownable is anything that is owned, regardless of whether it has monetary value.

Dave: Maybe we don't need an `Ownable` class, since the types of things can be enumerated.

gist has a predicate `owns`.

Dave: Distinction between possession, control, and beneficial ownership.  

Dan: Mortgages can be sold.

Dave: "Selling" a mortgage means transferring the right to receive the money, not the actual ownership. A lender owns a mortgage, which is an asset. A person's mortgage is a liability and an obligation - you can't destroy it, you are required to have insurance on it, etc.

Jamie: A mortgage is not owned, it's a contract.

Peter: There can still be obligations after you pay off the mortgage - e.g., is it's in a historical district.

Dan: Add `Asset` rather than `Ownable`.

Jamie: Do assets mean just physical assets?

Dan: Asset is broader, but could subclass as physical asset, intangible asset. Include subclasses in gist?

Currently in gist an `Account` is an `Agreement`, which is a `Commitment`.

Dave: if you have the obligation, it's a liability. If you're the obligee, it's an asset. 

Dave: an account is an agreement.

Rebecca:

**Comment by rjyounes** [comment]
Dan: 
- Asset vs Ownable - Asset has value, an Ownable thing may have no value. 
- Arose at a client wanting to account for software and other things owned.

Rebecca/Michael:
- Is there an advantage to have a class Ownable as opposed to assertions that X owns Y? Is there value to knowing that something can be owned?

Michael: Is Ownable abstract, or would people assert instances into it?

Dan: Asset is more concrete, would want to create instances, but add something in definition referring to ownership.

Dave: Asset occurs in gist accounting. Do we want to push it up to gist core? Definition: gist:Artifact && hasMagnitude some Monetary && someone beneficially owns it.

Jess: Machinery being tracked - owned by vs used by

Michael: Leave in gist accounting

Dan: Ownable is a subclass of (PhysicalIdentifiableObject U Artifact U IntellectualProperty U Right)

Peter: some rights are inheritable, others die with you.

Question 1: Do we want either Asset or Ownable in gist core?
Question 2: How to define it?

Dave: Asset in accounting is more limited.

Michael: Ownable used to be part of gist, then it was removed. Votes against Ownable. Simple definition of Asset: has value and owned by someone. Fundamentally based on a relationship, so it's a role. We don't often define such classes.

Jess: Whether something has value depends on circumstances.

Dan: Agrees that Michael's point is a good reason for leaving out of gist core. OK either way.

Jamie: A lot of companies track assets. How would that be recorded in a KG?
Michael: With ownership relationships

Dave: Sometimes "asset" means something very specific depending on context. 

Dan: Unlikely to mint an instance of Asset; would generally be a physical thing, account, etc.

DECISION: Will not define either class.
