### ISSUE TITLE
Update all labels according to a standard convention (replaces #20)

### ISSUE THREAD

**Issue by DanCarey404** [semanticarts/gist#227]
Add/replace rdfs:label values according to the agreed-to standard.

**Comment by rjyounes** [comment]
@DanCarey404 Can you please add a summary of the agreed-upon standard so that it is documented here? Then can #20 be closed?

**Comment by rjyounes** [comment]
Replaces #20

**Comment by DanCarey404** [comment]
**Per Rebecca's request, these are the labeling standards being implemented.**
#### Classes
- Sentence case
- Normalized to natural language standards. E.g., hyphens inserted, acronyms in all caps, etc.
  - Examples: _AMA guideline_, _ISBN-10_
  
#### Properties
- Same as classes, but initial lowercase 
- Examples: _has unit of measure_, _has SSN_.

**Comment by rjyounes** [comment]
Just to clarify: this was not my _request_: it was my _proposal_, which the group discussed and agreed on. :)

**Comment by rjyounes** [comment]
Why is this a minor rather than a patch change?

**Comment by rjyounes** [comment]
This task needs an assignee.

**Comment by uscholdm** [comment]
@sa-bpelakh Boris has a query for this. Can you pop it into this issue, for convenience?

**Comment by sa-bpelakh** [comment]
What I have are SHACL rules that validate that labels are conformant: https://github.com/semanticarts/platts-ontology/blob/develop/shapes/ontologyShapes.ttl. They enforce the policy described above, and even detect acronyms in all caps (minimum of 2 letters, I believe) and ignore their casing. The current version does _not_ allow for numbers in class or property names, so if that's a requirement, we'll have to make some changes.

**Comment by rjyounes** [comment]
I think we should allow numbers; e.g., hypothetically we could define classes like Shimano105Components, Iso639 (subclass of Category), TourDeFrance2020Racers, CharactersIn1984, ...

**Comment by sa-bpelakh** [comment]
I can see that for a specific domain, but for the base gist? We can set up a fun game of [regex golf](https://alf.nu/RegexGolf) for labels.

**Comment by rjyounes** [comment]
Maybe it's less likely in an upper ontology, but why exclude it in principle?

**Comment by uscholdm** [comment]
> Maybe it's less likely in an upper ontology, but why exclude it in principle?

We get to choose our own stylistic conventions, as does each client project.  I don't think we want gist to have numbers in IRIs and a rule for this would find a one the looks exactly like a lower case el. So I vote to put it in our gist checks as a warning.

**Comment by rjyounes** [comment]
If we disallow numbers in local names, and we happen to come across the need for one, we are then forced to spell the number out, which I think is worse. What's wrong with numbers in IRIs?

A reminder that this issue is the implementation of a set of conventions that had already been decided on and documented in the gist style guide. The point is not to revisit the decisions here.  Quoting from the style guide that we had agreed on:

- Alphanumeric characters only.
  - Example: `Isbn10`, not `Isbn-10` or `ISBN-10`.

This issue surfaced because I want to find a new assignee, since we agreed on the implementation back in April and have been postponing it since them.

**Comment by rjyounes** [comment]
@sa-bpelakh Aren't the SHACL rules configurable in the YAML file, so, e.g., Platts and gist could have different naming conventions?

**Comment by uscholdm** [comment]
Its true that this issue should not get into what the style conventions are. That can be debated in  a separate issue if anyone care enough to raise it.

**Comment by sa-bpelakh** [comment]
@rjyounes Yes, the bundle file configures which shapes to apply. So we can configure whatever we consider appropriate for gist, and customers can, um, customize 😄 whichever way they want.

**Comment by marksem** [comment]
Team has disagreement on the naming convention as of 12/10/2020 issues meeting.  @DanCarey404 will poll SA ontologists.  While there IS consensus to follow the standard, there is not consensus ON the standard.  

PS @sa-bpelakh will modularize the SHACL checking to allow ease of applying different conventions based on where starndard lands.

**Comment by rjyounes** [comment]
@marksem @DanCarey404 Can we please move discussion of this issue to a gist review meeting and notes here? Our goal is to be transparent, and decisions made by internal polling are not. In addition, there needs to be a rationale for reopening a decision that was made months ago. We cannot rethink every issue for those who haven't been attending meetings.

**Comment by rjyounes** [comment]
My input, based on earlier decisions now recorded in the gist style guide:

### Classes

- Sentence case
- Normalized to natural language standards. E.g., hyphens inserted, acronyms in all caps, etc.
  - Examples: _AMA guideline_, _ISBN-10_
  
### Properties

- Same as classes, but initial lowercase
- Examples: _has unit of measure_, _has SSN_.

### Rationale

We adopt sentence over title case because the latter, while technically well-defined, has more complex rules and can introduce inconsistencies when implemented by different users.

Further notes:


- Sentence case vs title case: I hold by the decision made earlier: We adopt sentence over title case because the latter, while technically well-defined, has more complex rules and can introduce inconsistencies when implemented by different users.
- Lower case for all properties, object and datatype
- Acronyms in labels: since I believe that labels (as opposed to local names) should be in natural language form, acronyms should be spelled as they normally are. I will note that UoM is not an actual English-language acronym and therefore is not an example of such. We should also be careful about when an acronym is a prefLabel and when an altLabel. There are cases where the acronym is the most common term (e.g., "CIA", "FBI") and therefore it should be the prefLabel and the fully-spelled out version should be the altLabel, but there are also cases of the reverse (e.g., "Electronic Arts" not "EA").
- Labels are meant to be in natural language, not camelcase etc. Therefore, hyphens are appropriate where they are used in natural language (in this case English) but not otherwise.

**Comment by uscholdm** [comment]
I find @rjyounes 's arguments and rationale compelling. If anyone wants to use labels for column headers then they can introduce a subproperty of altLabel called, say titleCaseLabel.

**Comment by rjyounes** [comment]
I didn't realize that one of the issues at stake in the renewed discussion was the use of labels as column headers. IMO that makes the case even stronger: it's hard to justify considering the _**preferred label**_ as one designed for column headings or any other implementation-specific use. We have actually had this discussion during review of #20, where we reached the same conclusion as in @uscholdm's suggestion above, to define additional annotations for application-specific needs. In the case of column headers, they are (or could be) the same as the local names, so one could parse the IRIs to derive the local names for use as column headers and not maintain the values in an annotation.

**Comment by DanCarey404** [comment]
I suggest that all words in a label have a leading capital.  One reason for this suggestion is that Notepad++ has a convert case option (Proper Case) which does that, as does MS Word (Capitalize Each Word).  This removes ambiguity from the rule and ensures the consistency that some are looking for.

**Comment by rjyounes** [comment]
@DanCarey404 Are you suggesting that even function words (prepositions, articles, etc) would be capitalized? That's not a type of casing I've ever heard of, other than the applications you mention. I don't know why anyone would ever want that.

**Comment by rjyounes** [comment]
One reason for using initial lower for properties: we use labels that are tied to the local names, and should preferably be derivable from them by some simple rules, such as adding whitespace at word boundaries indicated by camel-casing. Since our properties have local names with initial lowercase, this suggests the labels should follow suit.

**Comment by rjyounes** [comment]
There are four logical options:

1. Title case for all: Temporal Relation, Has Giver
2. Title case for classes, lower case for properties: Temporal Relation, has giver
3. Sentence case for all: Temporal relation, Has giver
4. Sentence case for classes, lower case for properties: Temporal relation, has giver.

Note: 2-4 make exceptions for acronyms and terms that are generally capitalized: Social Security Number, has SSN, has Social Security Number.

We haven't mentioned taxonomy terms. There are three possibilities here:
1. Title case
2. Sentence case
3. Lower case

And individuals: these are perhaps logically title case since they function like proper names: Semantic Arts, United States Department of Defense, etc.

**Comment by rjyounes** [comment]
Notes from 2021-01-14 triage meeting:

Dave: When do we see labels?

Graphics
Forms
Which would you rather see?
Rebecca: we also see them in documentation (e.g., Widoco)

Peter: accuracy more important than typographic consistency

Will vote next meeting.

**Comment by uscholdm** [comment]
Thank you @rjyounes for comprehensive summary. 

> Conclusion: There are no generally accepted conventions; we should choose whichever one we like best.

Exactly.

> We haven't mentioned taxonomy terms.

Most taxonomy terms are instances of `gist:Category`, which is a lot like a class, semantically.  the key technical difference is that we use `gist:categorizedBy` instead of `rdf:type` to indicate what kind of thing something is. So we may want to adopt the same convention for taxonomy terms as we do for Classes.

**Comment by rjyounes** [comment]
These are the logical options for class and property labels:

1. Title case for all: Temporal Relation, Has Giver, Identified By (in title case, prepositions at the end of a phrase receive stress and are in upper case)
2. Title case for classes, lower case for properties: Temporal Relation, has giver
3. Sentence case for all: Temporal relation, Has giver
4. Sentence case for classes, lower case for properties: Temporal relation, has giver
5. ~Same as local name: TemporalRelation, hasGiver~
6. ~Lower case for all: This has not been mentioned and I doubt if anyone wants it; we can probably rule it out.~
7. ~Every word upper case: Has Unit Of Measure~

Offline voting yields #2 as the winner.

Rebecca will compile a short list of title case conventions for consideration at next meeting.

**Comment by rjyounes** [comment]
From Wikipedia:

```
The rules of title case are not universally standardized. The standardization is only at the level of house styles and individual style guides. Most English style guides agree that the first and last words should always be capitalized, while articles, short prepositions, and some conjunctions should not be. Other rules about the capitalization vary.
```

So I assume the following Universal rules, and show additional specifications under Variants. I've omitted definitions from non-authoritative sites such as grammer-monster.com, grammar.yourdictionary.com, capitalizemytitle.com, etc.

Universal rules
1. Capitalize first and last words
2. Articles, short prepositions, and some conjunctions are not capitalized

Variants (omitting some details about Latin words and words starting with a Greek letter):
**work in progress - to be completed later**

**Comment by uscholdm** [comment]
> Capitalize first and last words

So if the class name was ThingWithMassAndWeight, the title case is "Thing with mass and Weight?"  That's odd. Surely Mass would be capitalized, would it not?

Michael

**Comment by rjyounes** [comment]
I forgot one. Note that this is incomplete. You may find examples that seem odd because I haven't yet provided the individual variants.

**Comment by rjyounes** [comment]
I've sorted through a number of style guides from reputable sources (AP, APA, Chicago Manual of Style, MLA, NYT, Wikipedia) . The details are included in the attached document as I think they will not be of general interest. I've come up with an amalgam of various conventions that is also computable (e.g., a rule that says to capitalize nouns, verbs, adjectives, adverbs, and pronouns is not computable), as follows:

1. Capitalize:
    a. First and last words
    b. Words of four or more letters
    c. Second part of hyphenated word (e..g, *Data-Centric*, not *Data-centric*)
1. Lowercase:
    a. Articles: *a*, *an*, *the*
    b. Conjunctions: *and*, *but*, *if*, *for*, *or*, *nor*, *so*, *yet*
    c. Prepositions: *as*, *at*, *by*, *cum*, *ere*, *for*, *in*, *of*, *off*, *on*, *out*, *per*, *pre*, *pro*, *qua*, *re*, *sub*, *to*, *up*, *via*,
1. Capitalize everything else

**Comment by rjyounes** [comment]
Regarding automated conversion of local names to labels: there's an issue in the conversion of acronyms. There are two possible local name conventions:
1. Represent as in natural language - generally all uppercase - e.g., `hasSSN`
2. Represent in camel case - e.g., `hasSsn`. The argument is that word boundaries can be easily detected. `isCiaAgent` allows word boundary detection, while `isCIAAgent` does not. Even for human users, the word boundary is easier to see in the latter.

However, labels should include natural language formats: *is CIA agent*, not *is Cia agent*. The correct version cannot be algorithmically computed from either local name.

The same may be true of hyphenated words, depending on the local name convention.  _ISBN-10_ can be automatically computed from `Isbn-10` or `ISBN-10 but not `Isbn10` or `ISBN10`.

 In fact, _in general it is easier to derive the local name from the label than vice versa_.

**Comment by uscholdm** [comment]
> In fact, in general it is easier to derive the local name from the label than vice versa.

Interesting observation, it usually goes the other way, but this sounds correct.

> The argument is that word boundaries can be easily detected. `isCiaAgent` allows word boundary detection, while `isCIAAgent` does not. Even for human users, the word boundary is easier to see in the latter.

I think it is easier to see the boundary in the former: `isCiaAgent` .  Was that a typo?

**Comment by rjyounes** [comment]
Yes, that's an error. I've fixed it above.

**Comment by rjyounes** [comment]
Title case proposal above accepted for implementation.

**Comment by rjyounes** [comment]
Boris will fix all labels, first by automation and then manual adjustment for exceptions.

**Comment by rjyounes** [comment]
In writing the label validation script (see PR #428), Boris noted that proper nouns in labels must also retain capitalization.  An emended version of the label conventions follows:

**Title Case Convention**
1. Capitalize:
     a. First and last words
     b. Words of four or more letters
     c. Second part of hyphenated word (e..g, _Data-Centric_, not _Data-centric_)
2. Lowercase:
     a. Articles: a, an, the
     b. Conjunctions: and, but, if, for, or, nor, so, yet
     c. Prepositions: as, at, by, cum, ere, for, in, of, off, on, out, per, pre, pro, qua, re, sub, to, up, via
3. Capitalize everything else

**Label Conventions**
Classes: title case (as above)
Properties: all lowercase 

The following exceptions apply to both class and property labels:
- Acronyms and proper nouns are kept intact (e.g., ```has SSN```, ```unit symbol Unicode```, ```ISBN-10```)
- Numbers are allowed (e.g., ```ISBN-10```)
- Hyphens are allowed (e.g., ```ISBN-10```)

The exception for proper nouns makes the convention not fully automatable.

The implementation of these conventions in current labels will be done by Boris using a script with manual corrections (for the non-automatable exceptions). To support label validation as part of bundling the ontology for release, we will add an additional ontology file with an annotation signaling to the validation script that the label is not subject to the validation rules. We propose ```gist:nonConformingLabel``` for the annotation. See additional notes in PR #428.
