### ISSUE TITLE
multiple owl:Thing anonymous individual declarations in GIST:Units

### ISSUE THREAD

**Issue by DougalW** [semanticarts/gist#295]
When I include GIST into my ontology, the base units have multiple owl:Thing anonymous individual declarations, which interferes with ontology processing in our schema service.

<img width="1233" alt="Screen Shot 2020-05-22 at 10 35 26 PM" src="https://user-images.githubusercontent.com/47440012/82659309-99e4ae00-9c7c-11ea-88f6-551912111e03.png">

Is this an artefact of the modularity / imports aspect of GIST?

**Comment by rjyounes** [comment]
There are several individuals which exhibit the same behavior. There may be a couple of things going on: the definition of gist:_ampere in gistTop includes a redundant owl:Thing assertion which should be removed (see #297). Since this individual is reference in another file, gistUnit, Protégé adds a stub declaration, which  it does for any term referenced but not defined in a file (a Protégé feature we dislike). Together these may produce the two type assertions. There are other individuals that have the redundant type assertion in the definition but are not referenced in another file - in these cases Protégé lists only one owl:Thing type; e.g., _one_millisecond, _meter. In a third case, e.g., _millisecond, there is no owl:Thing assertion in Protégé, and also none in the definition. 

The solution lies in removing all the owl:Thing assertions (#297).

**Comment by rjyounes** [comment]
I believe this will be fixed in the next release. The tool that builds the release package will remove the Protégé stub declarations. @sa-bpelakh can you confirm?

**Comment by sa-bpelakh** [comment]
I have not yet implemented the stub removal code, all I added in my last set of changes was not to add `rdfs:isDefinedBy` to those stubs. But I agree that we should remove these automatically.

**Comment by uscholdm** [comment]
@rjyounes @sa-bpelakh There is only one, not two for gist:_ampere in 12.0.0.  Is this something we still want to address?

![image](https://github.com/semanticarts/gist/assets/10777545/c3bae7ee-f818-4bae-a506-b7d149f94e30)
