### ISSUE TITLE
Add language tags to all annotation strings

### ISSUE THREAD

**Issue by gregid** [semanticarts/gist#311]
Allow for annotations in other languages, or multiple languages.

**Comment by rjyounes** [comment]
Solution discussed but not finalized: the pre-commit hook should add "@en" to any string that doesn't already have a language tag. This should not be part of the release process because (a) the release process should not modify the strings, and (b) we want these changes to be added permanently to the repository.

There are two parts to this solution: 
- Add to the pre-commit hook
- Update style guide

**Comment by rjyounes** [comment]
Currently no use case for gist.

Jamie: 
- SPARQL 1.2 - there was one proposal to address issues around coalescing language tags and simplify the queries
- Will be using language tags for DCA and IBB
- Since we're also changing annotations, this would be a good time to add language tags. Old rdfs labels would stay without language tags.

MarkW: separate questions of what gist should do, what client projects should do, and what DCA should do.
A user could do a SPARQL update to add language tags if they want.

Michael proposes deferring this issue, they are implementing at Platts and can report back on how it works.
 
DECISION: Close and reopen if it becomes relevant again.

**Comment by rjyounes** [comment]
SPARQL 1.2 discussion here: https://github.com/w3c/sparql-12/issues/13

**Comment by gregid** [comment]
I'll understand if you decide not to implement it (it's your project after all) but I disagree there is no use case.
Using gist in languages other than English is unnecessarily complicated now. Mixing normal strings with language strings doesn't work well with most tools (e.g. Protege) which forces an user to first change original strings to EN lang string and only then to add additional language labels. Then repeat the process with every new gist release.

**Comment by uscholdm** [comment]
We accept that use cases may arise.  We are saying that we do not have any strong drivers for adding language tags to gist at the moment.  One of our clients does in fact want to use language tags. We will learn from that exercise about the pros and cons of different approaches and will have a better understanding of what is best for gist overall. One aspect is the impact on querying.

**Comment by rjyounes** [comment]
@gregid makes a good point: do we have a contingent of users outside the English-speaking world that are using gist?
