### ISSUE TITLE
Replace toAgent/fromAgent and toPlace/fromPlace with to/from

### ISSUE THREAD

**Issue by uscholdm** [semanticarts/gist#321]
PROBLEM:
Currently gist has the four properties: `toAgent/fromAgent` and `toPlace/fromPlace`.  This breaks the good practice of excluding  domains or ranges from property names. It forces unnecessary proliferation of properties. We just identified the need for moving money **from** one account **to** another account. An account is not a `gist:Place`, nor is it an 'agent' which does not exist in gist anyway. The range of `toAgent` is: `(gist:Address or gist:Organization or gist:Person)`. This will require creating yet another to/from pair of properties for what ever we decide money can go to or from. Might be a person, might be an account, might be something else that I can't think of at the moment. So creating toAccount/fromAccount might not be future-proof.

PROPOSAL:
1. create two new properties: `gist:to` and `gist:from` with no domain or range.
2. remove the properties `toAgent/fromAgent` and `toPlace/fromPlace`

If anyone feels the need to break  good practice by including ranges in property names, they can do so in their own ontologies and make them subproperties of `gist:to` and `gist:from`

**Comment by rjyounes** [comment]
We have fromAgent/toAgent, fromPlace/toPlace, fromNetworkNode/toNetworkNode.

Proposal: 
- Define general from/to predicates with no domain and range.
- Deprecate existing predicates.

Dan: Without distinct predicates you can't use the property to infer class membership.
Michael: But you can state restrictions to allow for those inferences.
Jamie: Even without the inferences, the thought process of what a predicate might infer an object into helps clarify what it is.
Rebecca: **we need more specific wording to make it more precise and not be subject to the semantic vagaries of English prepositions. Propose hasOrigin and hasDestination.**

**Comment by rjyounes** [comment]
Here's a note that was recorded on #131: Dave has agreed to change to general to/from predicates. On 2/9/20 he wrote: In general I like economizing on properties. I’m try to recall what ambiguity we were trying to prevent when we adopted those. I’ll think on it tonight. If I don’t come up with anything go ahead.

So in this case the solution would not be expanding the range of toAgent and fromAgent, but to define general to and from predicates with no ranges to incorporate Place and more.

However, I now think the semantics are so murky that we shouldn't touch this. Sending something to or from a place is not like sending it from or to a person. Perhaps the narrower issue of removing address from the domain/range of from/toAgent is all that we should do now. Sending from/to an Address is actually more like from/to a Place, so we could include Address with the from/toPlace domain/range instead.

**Comment by rjyounes** [comment]
Discussion on Teams 2020-10-08:

Rebecca: Note that ignoring the infinitival "to", the OED online identifies 16 different meanings and sub-meanings of the preposition "to" and 14 for "from." ... I think we have to be careful about the destination concept. Giving a gift to someone is not exactly like sending it to his/her home. Which may be why we have the from/toAgent and from/toPlace distinction. 

Boris: You are correct, there are different meanings there.

Rebecca: We may want to go back to a narrower issue from #131, removing Address from the from/toAgent domain and range. Sending to an address is more like sending to a place than it is like to a person. 

Jamie: There is a (intended) recipient (Person or Organization or Department (such as accounting, legal) & maybe Public Domain) and destination (address: physical address, email, dropbox account, bank account, etc). With similar concepts for the originating side. So you probably need to know 2 concepts on each side of a transfer.

Rebecca: The question isn't about knowing the types of objects on each side of the transfer, but rather assessing whether the transfer is enough the same semantically in the various cases to use the same predicate for all. I am now tending to think that they are not sufficiently the same. While we should not create different predicates simply due to differences in the type of subject and/or object - e.g, we don't have isMemberOfClub and isMemberOfChurch because the membership relationship is the same - I now think that a transfer such as one person giving another a gift is quite different from a person sending an object to an office, _on both sides_, and warrants a different predicate.

**Comment by uscholdm** [comment]
@rjyounes  
I propose that we close this, even though no agreement was reached.  It does not seem to be causing a problem for the time being.

**Comment by rjyounes** [comment]
Closing - will not fix.
