### ISSUE TITLE
Resurrect SocialBeing

### ISSUE THREAD

**Issue by rjyounes** [semanticarts/gist#329]
Granted SocialBeing was a union class (Person U Organization), it serves a useful function, and when a union appears repeatedly in axioms that is a signal that it has semantic significance / forms a natural class. The name could be improved upon.

Further suggestive evidence: a Google search of "people and organizations" (in quotes) yield 51.9 million results. A Google search of "organizations and people" (in quotes) yields 30.6 million results. By contrast, a Google search of "people and spacecraft" yields 143K results; "people and hospitals" returns 5.9 million. In other words, people and organizations constitute a commonly-used grouping.

**Comment by uscholdm** [comment]
Dave got rid of it because it is an abstract class.  Not having it does result in repeated appearances in e.g. domains and ranges which as you say suggests it has semantic import.  Dave prefers to have that repetition because it forces the ontologist to give due consideration to what is really meant each time it is used.  Its a minor nuisance. It's easy to add back in any enterprise ontology you are building.

**Comment by uscholdm** [comment]
@rjyounes 
This is no longer being considered.   The policy is to use a blank node, `(Person or Organization)` instead. Anyone who wants it can add it on their own.
