### ISSUE TITLE
Add properties for year precision to new time model

### ISSUE THREAD

**Issue by stewardont** [semanticarts/gist#388]
Just like DateInstant, but with precision of a year. Useful when we want to store data about which year something happened.

**Comment by uscholdm** [comment]
**Punch Line**: I recommend not putting this into gist. It is perfectly consistent, but we pushed hard on this for Platts and decided to do it differently.  But I worked it out in detail both ways on different branches in the platts-ontology repo on github.
1. Using gist:TimeInstant:   see the feature/calendar branch 
2. Using pleo:TimeInterval: see the feature/time-interval branch

**Details**
I just did exactly this for Platts, along with a bunch of other things.  I created MonthInstant, QuarterInstant and other such things for winter and summer seasons that the natural gas industry pays attention to.   It gets complicated because you cannot assume that a year instant will start on the 1st of the year, nor that a third quarter will start on Jul 1 etc.  A 'year' in the gas industry starts on Oct 1. Winter for the gas industry starts on Oct 1 in the EU but on Nov 1 in North America.  Fiscal years and quarters start at arbitrary places.  It was a workable solution that we put to the client.

In the end, the client (and me and Boris) found that talking about 'instants' that last a long period of time was non-intuitive and confusing.  The simple fact of the matter is there is no such thing as a gist:TimeInstant that is not really a time interval, in practice. Even if you go to the precision of nanosecond. Talking about a YearInstant makes the fact that it is an interval more in your face. 

So instead of representing time intervals as gist:TimeInstant(s) that have a precision that is acting like a duration, we brought back TimeInterval and a subclass of gist:Category called TimeIntervalType.  See the examples below. The gist:sequence triple says N for the Nth month, or the Nth quarter.   To identify a time interval only requires a start time and a duration, from which an endTime can be computed.  These decisions were driven in part by query needs.  For example: 

```
pleod:_TimeInterval_NaGas_Winter2020-21 a pleo:TimeInterval ;
    skos:prefLabel "NA Gas Winter 2020/2021" ;
    gist:categorizedBy pleox:_TimeIntervalType_NaGas_Winter ;
    pleo:startTime "2020-11-01T00:00:00"^^xsd:dateTime 
    .  
pleox:_TimeIntervalType_NaGas_Winter a pleo:TimeIntervalType ;
    skos:prefLabel "NA Gas Winter" ;
    skos:definition "Indicates that the time interval corresponds to when the five winter months occur for the NA gas market."^^xsd:string ; 
    skos:example "NA Gas Winter 2020/2021"^^xsd:string ; 
    pleo:hasGeneralizedDuration pleox:_TimePeriod_FiveMonths ;
    gist:sequence "2"^^xsd:integer ;
    .
pleox:_TimePeriod_FiveMonths
	a pleo:TimePeriod ;
	skos:definition "An inexact duration of time from one moment to another moment exactly five months later in the calendar year."^^xsd:string ;
	skos:example "The length of time between 9:00AM January 23, 2019 and 9:00AM July 23, 2019"^^xsd:string ;
	skos:prefLabel " Five Months"^^xsd:string ;
	skos:scopeNote "Although the exact duration varies due to variable length months, given the beginning or end of a particular five months on a timeline, you can find the exact end or beginning of that five months, respectively."^^xsd:string ;
	pleo:hasBasePeriod pleox:_BaseTimePeriod_Month ;
	gist:decimalValue "5"^^xsd:double ;
	.
pleox:_BaseTimePeriod_Month
	a pleo:BaseTimePeriod ;
	skos:prefLabel "Month"^^xsd:string ;
	pleo:numberOfPeriodsPerYear "12"^^xsd:integer ;
	.
```

```
pleod:_TimeInterval_March2020 a pleo:TimeInterval ;
    skos:prefLabel "March 2020" ;
    gist:categorizedBy pleox:_TimeIntervalType_March ;
    pleo:startTime "2020-03-01T00:00:00"^^xsd:dateTime 
    .
pleox:_TimeIntervalType_March a pleo:TimeIntervalType ;
    skos:prefLabel "March" ;
    skos:definition "Indicates that the time interval corresponds to when the month March occurs."^^xsd:string ; 
    skos:example "March 2020"^^xsd:string ; 
    pleo:hasGeneralizedDuration pleox:_BaseTimePeriod_Month ;
    gist:sequence "3"^^xsd:integer ;
    gist:partOf pleox:_TimeIntervalType_FirstQuarter ;
    .
pleox:_BaseTimePeriod_Month
	a pleo:BaseTimePeriod ;
	skos:prefLabel "Month"^^xsd:string ;
	pleo:numberOfPeriodsPerYear "12"^^xsd:integer ;
	.
```

**Comment by uscholdm** [comment]
This is related to issue: https://github.com/semanticarts/gist/issues/340

**Comment by rjyounes** [comment]
There's extensive discussion in #340, as Michael points out, but I'll just highlight the fact that the concept requested here is of a "calendar year" rather than a YearInstant. The latter can be from March 15, 1920 - March 14, 1921, whereas a calendar year would be 1920 or 1921. A calendar year is a type of YearInstant, probably. The example given for DateInstant is somewhat misleading because it also happens to be  calendar day, which is similarly is a type of DateInstant, but there are other DateInstants that are not.

**Comment by Jamie-SA** [comment]
@uscholdm have you looked at the links from @pwin about a standard way to represent common things like years & quarters? Would it be useful for your situation?

https://www.epimorphics.com/using-interval-set-uris-in-statistical-data/
https://github.com/epimorphics/IntervalServer

**Comment by rjyounes** [comment]
Two concepts: precision (dates, year) and durations (24 hours, 365 days). New time model is a calendar unit with some precision, not the duration.

Planned events wouldn't have a year or microsecond precision, but they can have a date and minute precision. Historical events can have any of these precisions.

DECISION: Add to new time model.

**Comment by rjyounes** [comment]
@DanCarey404 Assigning to you because it gets folded into the new time model.

**Comment by rjyounes** [comment]
Dependency: Do this after the new time model has been merged to develop.

**Comment by rjyounes** [comment]
In the new time model this would require four new properties:

```
plannedStartYear
plannedEndYear
actualStartYear
actualEndYear
```

Do we want to add four new properties to gist, or do we want to leave it to users to implement?

**Comment by uscholdm** [comment]
I think it makes sense to include them.

**Comment by dhurlburtusa** [comment]
Will this also handle adding `gist:_year`? Something like:

```trig
gist:_year
	a
		owl:NamedIndividual ,
		owl:Thing ,
		gist:BaseUnit
		;
	rdfs:isDefinedBy <https://ontologies.semanticarts.com/o/gistCore> ;
	gist:convertToBase "365.25"^^xsd:double ;
	gist:hasBaseUnit gist:_day ;
	.
```
And maybe
```trig
gist:_one_year
	a
		owl:NamedIndividual ,
		owl:Thing ,
		gist:Duration
		;
	skos:definition "A duration equal to 1 year."^^xsd:string ;
	skos:prefLabel "one year"^^xsd:string ;
	skos:scopeNote "This is a gist:Magnutude, not a unit of measure, it means essentially the same thing as the unit, year."^^xsd:string ;
	gist:hasUnitOfMeasure gist:_year ;
	gist:numericValue "1.0"^^xsd:double ;
	.
```
I'd like to use `gist:_year`.

**Comment by rjyounes** [comment]
@dhurlburtusa Sorry, this issue should have been closed. Can you please make a new issue to add `gist:_year`? The value of `hasBaseUnit` must be a base unit, which is therefore `gist:_second` - the base duration unit. Let's not add `gist:_one_year` right now, because there's an open issue regarding whether we should distinguish these magnitudes from their corresponding units. See #61.

**Comment by uscholdm** [comment]
> Let's not add `gist:_one_year` right now, because there's an open issue regarding whether we should distinguish these magnitudes from their corresponding units. See #61.

Given that `gist:_one_year`  was only created for use as a precision with TimeInstant, it should never be brought into gist proper.
