### ISSUE TITLE
Add gist:description

### ISSUE THREAD

**Issue by Jamie-SA** [semanticarts/gist#425]
We have many places where we'd like to add a user description field on various instance data and there doesn't seem to be a good existing choice for this. It seems general enough that it could be a candidate to go into gist.

**Comment by uscholdm** [comment]
I usually use `skos:definition` for instance descriptions.  Most of the time there is no need for anything else.  Would that not work for the cases you have in mind?

**Comment by rjyounes** [comment]
Definition and description are not equivalent. I can describe someone as medium height, brown hair, blue eyes, etc. but that is not a _definition_. The description is likely relevant only to instances, rather than classes and properties.And it's best thought of as a datatype property, I think: even though it's only text, it is data rather than metadata.

rdfs:comment is too vague, which is the reason we removed it from our standard set of annotations. I like the idea of adding gist:description.

**Comment by Jamie-SA** [comment]
A description and a definition are not semantically the same thing. So `skos:definition` would work if you don't mind using terms for things other than what they were meant for. Which seems to go against the general premise of semantic modeling. OTOH, I know we don't recommend a proliferation of datatype properties. So I am interested in hearing what other people think about wrt if it makes sense to make the distinction, and if it belongs in gist.

It isn't that I "need a solution" as I know there are many other options including `rdfs:comment` or we can add it to our own ontology. Heck, I could even use gist:containedText, but that wasn't what that was meant for either.

**Comment by rjyounes** [comment]
@Jamie-SA containedText was manufactured to go with a Text object, although the domain is not stated. Semantically it doesn't work anyway: we don't say the description "blue eyes, brown hair" is _contained_ by the person being described.

I agree with not overloading terms.

**Comment by Jamie-SA** [comment]
@rjyounes that was my point.

**Comment by uscholdm** [comment]
Definition is indeed different from description. `skos:scopeNote` can be used for descriptions. If we want something more specific than that, we could create a gist annotation property and have it be a subproperty of `skos:scopeNote`.  I don't yet see a good reason to use a datatype property.

**Comment by rjyounes** [comment]
I think you are mixing domains. The definition of skos:scopeNote is "A note that helps to clarify the meaning and/or the use of a concept." The description of John as "medium height, blond hair, blue eyes" does not clarify the meaning or use of John, nor is John a concept.

**Comment by uscholdm** [comment]
> The description of John as "medium height, blond hair, blue eyes" does not clarify the meaning or use of John, nor is John a concept.

Objection sustained.

**Comment by uscholdm** [comment]
@rjyounes says:

> [the description] is best thought of as a datatype property, I think: even though it's only text, it is data rather than metadata.

I am not compelled by that argument for making `gist:description` a datatype property.  

A property for description is similar to `skos:definition` in that it provides important semantic information.  So it makes sense for it to be an annotation property, a sibling of `skos:definition` and thus a subproperty of `skos:note`. They might even be kissing cousins.

**Comment by rjyounes** [comment]
Compare the function and content of a datatype vs annotation property in the following example:

```
:_UnitedNations a gist:Organization ;
   gist:name "United Nations" ;
   gist:description "The United Nations is an intergovernmental organization that aims to maintain international peace and security, develop friendly relations among nations, achieve international cooperation, and be a centre for harmonizing the actions of nations." ;
   skos:note "Do we really want to define this in gist?" ;
.
```

IMO the description is _data_ - in the same way that gist:name is - while the annotation is _metadata_.

Along these lines, I've been thinking about gist:name vs skos:prefLabel, and I've concluded that individuals that have real names in the real world should in general not have prefLabels, but rather names (though I don't rule out the possibility that labels would be appropriate in some contexts). Consider the lengthy discussion about how to format prefLabels in #227; you wouldn't have this discussion about the United Nations, because the name is an actual fact that has been assigned to the individual in the outside world, not something we assign. Instead of altLabel, one could define a hierarchy of name properties, such as abbreviation, acronym, legalName, genericName, givenName, familyName, etc. to provide other names like "UN," and so on. These tell you the semantics of the names and how they are used, as opposed to altLabel. I'm not proposing that all of these would be defined in gist itself - though abbreviation and acronym are universally useful, and legalName may be generally useful in an enterprise context.

**Comment by uscholdm** [comment]
> Along these lines, I've been thinking about gist:name vs skos:prefLabel

@rjyounes This is important and should be a separate issue.

**Comment by uscholdm** [comment]
> skos:note "Do we really want to define this in gist?"

This should be a `skos:editorialNote`. As you point out, it has nothing to do with the meaning of an IRI.   
* `skos:editorialNote` "A note for an editor, translator or maintainer of the vocabulary."

However all of the following have a LOT to do with the meaning of an IRI
* `skos:definition`: "A statement or formal explanation of the meaning of a concept."
* `skos:scopeNote`:  "A note that helps to clarify the meaning and/or the use of a concept."
* `gist:description`:  Further elaborates the meaning of a URI beyond what may be in `skos:definition` 


Having `gist:description` as an annotation is consistent with common usage. Textual information about the meaning of IRIs typically goes in annotations. That is what `rdfs:comment` is for.

**Comment by rjyounes** [comment]
I'm not suggesting that the skos properties be datatype properties. I do not see how the description of a person, organization, or other RWO can be considered meaning or use. It's exactly the same argument I made above for why skos:definition shouldn't be used instead of a description property. I maintain that the skos predicates are metadata about concepts - which is what ontology terms are - while a description is suitable for instances.

**Comment by rjyounes** [comment]
Moved the name discussion to new issue #427.

**Comment by uscholdm** [comment]
> How does your proposed definition of gist:definition distinguish it from skos:scopeNote?

Good question. Strictly speaking, it does not. So we could decide to just use `scopeNote` instead of a new property.   I don't see any proposed definitions for `gist:description`?  What do you propose? What distinguishes it from `scopeNote`?

**Comment by uscholdm** [comment]
> I do not see how the description of a person or other RWO can be considered an indication of its "meaning and/or use".

What does `foo:23456HJYf` mean? You have no idea. But suppose I say:
```
foo:23456HJYf a gist:_Organization ;
    skos:prefLabel "Office of Compliance"^^xsd:string 
  .
```
You now have an idea of what `foo:23456HJYf` is intended to mean. But you might not know anything about that office.  So it still might not mean much of anything to you.  This extra triple would help you:
```
foo:23456HJYf 
    gist:description l "A US federal organization that advances workplace rights, safety, health, and accessibility in the Legislative Branch."^^xsd:string 
  .
```

Now you have a fairly good grasp of what `foo:23456HJYf` means.  We could use `scopeNote`  to disambiguate it from other organizations with the same name.

**Comment by uscholdm** [comment]
PUNCH LINE: Sometimes the distinction between definition and description is not so clear cut. Sometimes it makes sense to use `skos:definition` for an instance, but due to likely confusion, I would recommend against it.

DETAILS: On the distinction between 'description' and 'definition'.  Every definition is a description, and one should never suppose that a description is a definition.  A lot of the time, there is no point in creating a `skos:definition` for instances which correspond to proper nouns in English.  But what would you call an entry in Miriam-Webster dictionary for [Ithaca](https://www.merriam-webster.com/dictionary/Ithaca)? 
* city in south central New York on Cayuga Lake population 30,014

If you were the author of the dictionary, I dare say you'd call it a definition.  It is intended to be a **definitive** characterization of what is meant by "Ithaca NY" -- so I would not find it jarring if someone used that phrase in a `skos:definition`. I might not do it that way, but it is not obviously wrong, semantically nor from a common sense perspective.

**Comment by rjyounes** [comment]
Whatever Merriam-Webster _thinks_ they're doing, I'm not buying it. Consider the MW entry for "George Washington":

1732–1799 American general; 1st president of the U.S. (1789–97)

I cannot be convinced that that's a definition. Does it mean that if he hadn't been a general or the first US president or lived one year longer he wouldn't have been the same person? 

The Ithaca case works too: if there are now 35K residents of Ithaca, is it a different city? By comparison, the definition of "thousand" really is, as MW states, "a number equal to 10 times 100." Any number that doesn't satisfy the definition is _not_ a thousand.

Further, there can be more than one city that matches the description "city in south central New York on Cayuga Lake population 30,014," which again suggests it's not a definition.

A definition is strict, in the sense that the thing so defined cannot change and remain the same thing. A description is malleable, in the sense that if the thing departs from its description it can still be the same thing, though the description needs to be updated.

I refer you to M-W's definition of "definition" (emphasis mine):
```
(1a) a statement of the _meaning_ of a word or word group or a sign or symbol 
(1b) a statement expressing the _essential nature_ of something
```

**Comment by uscholdm** [comment]
Given a strict definition of the word 'definition' then I agree with your latest remarks, and none of what you say seems to contradict the PUNCH LINE of what I said above which is about common broader usage of the term, 'definition' as well as common use of `skos:definition`.   

So I don't see much daylight between a decision you would make about this or one that I would make in an ontology creation exercise.   We should strive to make our `skos:definition`s in gist more strict.  Most of the current entries do not even come close to your exacting standards.

**Comment by rjyounes** [comment]
Comment from Michael at triage meeting: everything needs a skos:prefLabel since UIs and other applications look for it.

This seems right.

**Comment by Jamie-SA** [comment]
I missed the meeting today so I don't have the context. I am trying to figure out how MU's comment applies to this issue?

**Comment by rjyounes** [comment]
DECISION: gist:description to be defined as a datatype property.
