### ISSUE TITLE
OrdinalMember should not be a subclass of Category

### ISSUE THREAD

**Issue by rjyounes** [semanticarts/gist#426]
```
gist:OrdinalMember
	a owl:Class ;
	rdfs:subClassOf
		gist:Category ,
		[
			a owl:Class ;
			owl:unionOf (
				[
					a owl:Restriction ;
					owl:onProperty gist:directlyPrecededBy ;
					owl:someValuesFrom gist:OrdinalMember ;
				]
				[
					a owl:Restriction ;
					owl:onProperty gist:directlyPrecedes ;
					owl:someValuesFrom gist:OrdinalMember ;
				]
			) ;
		]
		;
	.
```

**Comment by uscholdm** [comment]
FROM @mkumba 

> It looks like gist:OrdinalMember in addition to a restriction is also a Category.  I don’t think that was intentional, was it?

**Comment by uscholdm** [comment]
I believe it was intentional - but it may not be what we want now. This arose when we were modeling different kind of sets of values for measurements.  OrderedMember and OrdinalMember were to allow for specifying order to qualitative values such as low, medium and high, as opposed to non-ordered categories like exempt and nonexempt or most uses of colors. 

However, I suppose one could imagine wanting to use this for non-Categories.  So it makes sense to relax this.

**Comment by rjyounes** [comment]
Subsumed by #112.
