### ISSUE TITLE
Remove sensor-related terms

### ISSUE THREAD

**Issue by rjyounes** [semanticarts/gist#462]
I think modeling of sensors is too domain-specific for an upper ontology.

Related terms (possibly incomplete):

```
hasViableRange
respondsTo
Controller
Sensor
Actuator
```

Look in old IoT module for others.

**Comment by uscholdm** [comment]
@rjyounes 
I agree. Let's bring this up to the group. Do we know where it would go?

**Comment by Jamie-SA** [comment]
Seems like IoT could belong in gistComputing if that includes hardware and devices.

**Comment by pmcb55** [comment]
I'm just curious - but rather than putting all that work into creating your own IoT extension, have you guys looked into re-using the 2017 **_W3C Recommendation_** for IoT - i.e., the Semantic Sensor Network (SSN) ontology (and it's 'Upper Ontology' for Sensor, Observation, Sample, and Actuator (SOSA) )?
I'm no expert in IoT or these ontologies, but one of my colleagues was working closely with them a few years ago, and I believe the latest evolution (from last month!) of the Editor's Draft is based on years of active industry use: https://w3c.github.io/sdw-sosa-ssn/ssn/

**Comment by rjyounes** [comment]
See also #729

**Comment by rjyounes** [comment]
DECISION: Remove from gistCore. Whether to add to gistComputing is TBD.

**Comment by turingtest37** [comment]
I propose moving these concepts to a new sub-gist. See Issue #1078.
