### ISSUE TITLE
Samples of triple modifications required to migrate to gist 11 datetime model

### ISSUE THREAD

**Issue by rjyounes** [semanticarts/gist#643]
As per issue #613, we will not provide a script for this migration, but instead examples of changed triples in a variety of conditions. Notes from #613:

Example: from triples

```markdown

:_x gist:hasPlannedEnd :_ti .
:_ti a gist:DateInstant ;
   gist:localDateTime "2022-03-16T01:01:01Z-04:00"^^xsd:datetime ;
   .

```

You create:

```markdown

:_x gist:plannedEndDate "2022-03-16T00:00:00Z-04:00"^^xsd:datetime .

```

Note that hours, minutes, and seconds must be zeroed out for date values. There are a lot of wrinkles. For example, in gist 10, the local datetime may not have an offset, but a value for `gist:usesTimeZoneStandard` instead. Precision could have been indicated either with `hasPrecision` or the subclass of `TimeInstant`. 

We have agreed that scripting this will take too much effort, but we will include sample changes covering a variety of conditions with the release.

**Comment by DanCarey404** [comment]
In writing up the instructions for handling the new gist time paradigm, I ran into what I believe to be a problem with the TimeZone and TimeZoneStandard classes.  
The current draft formal definition for TimeZone is "gist:GeoRegion and (gist:hasOffsetToUniversal some gist:Duration)". The definition for TimeZoneStandard is "gist:Specification and (gist:isBasedOn some gist:TimeZone)".
I believe we have these a bit backwards because I cannot figure out how to create meaningful instances of these.  
Instead, I think that TimeZoneStandard should be "gist:Specification and (gist:timeOffset some xsd:duration)", and TimeZone should be "gist:GeoRegion and (gist:isAffectedBy some gist:TimeZoneStandard)".

This requires bringing back the gist:timeOffset property I had in my original proposal.
    gist:timeOffset rdf:type owl:DatatypeProperty ;
        rdfs:range xsd:duration .

Example usage
    :_TimeZoneStandard_easternStandard gist:TimeZoneStandard ;
        gist:timeOffset "-PT5H"^^xsd:duration .
    :_TimeZoneStandard_easternDaylight gist:TimeZoneStandard ;
        gist:timeOffset "-PT4H"^^xsd:duration .
    :_TimeZone_usEastern a gist:GeoRegion ; 
        gist:usesTimeZoneStandard :_TimeZoneStandard_easternDaylight .
    :_Event_x gist:plannedDateTime "2022-06-08T09:00:00"^^xsd:dateTime ;
        gist:usesTimeZoneStandard :_TimeZoneStandard_easternDaylight .

I'm open to keeping the current draft entities if someone can show me how they would appropriately applied.
Thanks.

**Comment by uscholdm** [comment]
It does seem backwards, but there are other problems. A `TimeZoneStandard` is an algorithm. But `:_greenwichTimeZone` is an instance of `TimeZoneStandard`. That might be a simple typo.

The datatype, `xsd:duration` is not part of OWL, so that won't fly.

I don't know how `usesTimeZoneStandard` is supposed to work. On first reading, the following do not clarify what the domain or intended domain are supposed to be or exactly what it means. The examples do not indicate what the subject of the triple might be.
- `skos:definition "The time zone, including daylight savings time adjustment, of an event or other object that can have a date and time."^^xsd:string ;`
- `skos:example "EST (Eastern Standard Time), PST (Pacific Daylight Time)."^^xsd:string`

Also, in Dan's example, could I say:
```
:_TimeZone_usEastern a gist:GeoRegion ;
                   gist:usesTimeZoneStandard :_TimeZoneStandard_easternDaylight , :_TimeZoneStandard_easternStandard .
```
This is a very different meaning of `gist:usesTimeZoneStandard` that to use it with an event as the subject.
Actually, maybe Dan is overloading the property gist:usesTimeZoneStandard. TimeZones don't use time zone standards, events do. 

I'm left still somewhat confused - I hope at least the comments move things along a bit.

**Comment by DanCarey404** [comment]
Per Wikipedia: "A time zone is an **area** that observes a uniform standard time.  All time zones are defined as **offsets from Coordinated Universal Time (UTC)**."  So a the UTC offset is the specification, i.e., the TimeZoneStandard.  The TimeZone uses the standard.  When we recently started using DST, I didn't change the TimeZone I am in (Eastern Time Zone), but the Time Zone started following a different Standard (an offset of -5hr for DST vs -4hr for standard time).
Also according to Wikipedia, "English speakers often use GMT as a synonym for Coordinated Universal Time (UTC) in modern usage, this is incorrect – **GMT is now a time zone, not a time standard**."

**Comment by rjyounes** [comment]
Note that a separate issue #650  has been created for the time zone issue.

**Comment by rjyounes** [comment]
Attaching Dan's draft.

[Time-Related Changes in gist v11.md](https://github.com/semanticarts/gist/files/8418563/Time-Related.Changes.in.gist.v11.md)

@pwin @dylan-sa If possible, we should make an html version of this as well. This could just be done manually since it's a one-off. They should be included in `/migration/v11.0`.

**Comment by rjyounes** [comment]
Cleaned up markdown in the attached file (my initials added to filename):

[Time-Related Changes in gist v11-RY.md](https://github.com/semanticarts/gist/files/8418864/Time-Related.Changes.in.gist.v11-RY.md)

**Comment by rjyounes** [comment]
This is excellent. I have only a couple of substantive comments:

- `gist:atDateTime` is a new property, but when you say "we have added a number of new sub-properties to the `gist:atDateTime` property..." it sounds like that was an existing property. Maybe "we have added a top-level `gist:atDateTime` property and a number of sub-properties."
- `hasSameEndTimeAs` would be a more idiomatic name. I realize this is just an example, but gist 10 had `isSameTimeAs`. I never understood the point of that predicate, because you can get it from date comparisons, which is even easier now that we are using datetime literals.

**Comment by DanCarey404** [comment]
Excellent suggestions, all.  I'll wait a bit to see what comments others might have, and then add your changes.

**Comment by DanCarey404** [comment]
I cannot remember whether these were included in the release 11 documentation or not.  But in any case, this ticket is resolved, IMO.

[TimeInstant_ReplacementInstructions.txt](https://github.com/semanticarts/gist/files/8968789/TimeInstant_ReplacementInstructions.txt)

**Comment by rjyounes** [comment]
They did get included in the documentation.
