### ISSUE TITLE
Issues relating to `TimeZone` and `TimeZoneStandard`

### ISSUE THREAD

**Issue by rjyounes** [semanticarts/gist#650]
Thread copied from Teams on 2022-04-04:

_Dan:_

In writing up the instructions for handling the new gist time paradigm, I ran into what I believe to be a problem with the TimeZone and TimeZoneStandard classes.  
The current draft formal definition for TimeZone is "gist:GeoRegion and (gist:hasOffsetToUniversal some gist:Duration)". The definition for TimeZoneStandard is "gist:Specification and (gist:isBasedOn some gist:TimeZone)".
I believe we have these a bit backwards because I cannot figure out how to create meaningful instances of these.  
Instead, I think that TimeZoneStandard should be "gist:Specification and (gist:timeOffset some xsd:duration)", and TimeZone should be "gist:GeoRegion and (gist:isAffectedBy some gist:TimeZoneStandard)".

 This requires bringing back the gist:timeOffset property I had in my original proposal.
    gist:timeOffset rdf:type owl:DatatypeProperty ;
        rdfs:range xsd:duration .

Example usage
```
    :_TimeZoneStandard_easternStandard gist:TimeZoneStandard ;
        gist:timeOffset "-PT5H"^^xsd:duration .
    :_TimeZoneStandard_easternDaylight gist:TimeZoneStandard ;
        gist:timeOffset "-PT4H"^^xsd:duration .
    :_TimeZone_usEastern a gist:GeoRegion ; 
        gist:usesTimeZoneStandard :_TimeZoneStandard_easternDaylight .
    :_Event_x gist:plannedDateTime "2022-06-08T09:00:00"^^xsd:dateTime ;
        gist:usesTimeZoneStandard :_TimeZoneStandard_easternDaylight .
```

_Rebecca:_

Given the definition of TimeZoneStandard  as "The algorithm for getting from Greenwich Mean Time to local time, which includes the time zone offset and rules about daylight savings time," it seems to me that there are not two standards, eastern standard and eastern daylight. Rather, this is one standard that has rules for when it switches from daylight to standard and back.
 
The definition does call for a time zone offset, however, but given that different time zones switch from daylight to standard on different dates, is this possible? If it is, then I'm in favor of it.
 
I prefer the semantics of gist:isBasedOn to gist:isAffectedBy, which is not specific enough, but I agree that we have it backwards - the time zone is based on the time zone started rather than the other way around.
 
I have a somewhat different idea of how this should go - I think an event takes place in a time zone, and is only indirectly related to the time zone standard through the time zone. This gives us triples such as:

```
:_TimeZoneStandard_eastern a gist:TimeZoneStandard .
:_GeoRegion_usEasternTimeZone a gist:TimeZone ;
    gist:isBasedOn :_TimeZoneStandard_eastern .
:_Event_x gist:plannedEndMinute "2022-06-08T09:00:00"^^xsd:datetime ;
    gist:isInTimeZone :_GeoRegion_usEasternTimeZone .
```

**Comment by rjyounes** [comment]
Refer to discussion on issue #643.

**Comment by rjyounes** [comment]
@DanCarey404  I've cleaned up the markup in the attached version
[Time-Related Changes in gist v11-RY.md](https://github.com/semanticarts/gist/files/8418675/Time-Related.Changes.in.gist.v11-RY.md)
.

**Comment by rjyounes** [comment]
DECISION:
* Remove TimeZone, TimeZoneStandard, and associated predicates, and greenwich mean time instance.
* Plan on a sub-gist to encompass a variety of time issues, such as time zones, calendars, fiscal periods, etc.

**Comment by Jamie-SA** [comment]
Brought this up with Dave today and he didn't have any major reservations about removing the TimeZone components.

**Comment by johnwcowan** [comment]
> Given the definition of TimeZoneStandard as "The algorithm for getting from Greenwich Mean Time to local time, which includes the time zone offset and rules about daylight savings time," it seems to me that there are not two standards, eastern standard and eastern daylight. Rather, this is one standard that has rules for when it switches from daylight to standard and back.

I think this is basically misworded:  it should say "includes the *standard* time zone offset.  Thus the America/New_York time zone has an offset of UTC-5 and a ruleset named "US".

**Comment by rjyounes** [comment]
That makes sense. I think you are in agreement with the general idea that the TimeZone is based on the TimeZoneStandard rather than the reverse. The ruleset would be more specific since a few states have their own rules; you probably mean something like "US default."

**Comment by johnwcowan** [comment]
"US" is the name of the modern U.S. ruleset for DST in the IANA time zone specifications.  Places without DST are considered separate time zones; for example, Arizona is time zone America/Phoenix because it is always (in modern times) on MST rather than alternating MST/MDT (which is America/Denver).

Most Americans think of the U.S. as having four time zones: Eastern, Central, Mountain, Pacific.  By current law, there are five more: Atlantic (Puerto Rico and the U.S. Virgin Islands), Alaskan, Hawaii-Aleutian, Samoan, Chamorro.  But from a historical perspective, which is what you need to convert an arbitrary Universal Time timestamp to local time, the U.S. is partitioned into 30 time zones:  America/New_York, America/Chicago, America/North_Dakota/Center, America/North_Dakota/New_Salem, America/North_Dakota/Beulah, America/Denver, America/Los_Angeles, America/Juneau, America/Sitka, America/Metlakatla, America/Yakutat, America/Anchorage, America/Nome, America/Adak, America/Phoenix, America/Boise, America/Indiana/Indianapolis, America/Indiana/Marengo, America/Indiana/Vincennes, America/Indiana/Tell_City, America/Indiana/Petersburg, America/Indiana/Knox, America/Indiana/Winamac, America/Indiana/Vevay, America/Kentucky/Louisville, America/Kentucky/Monticello, America/Detroit, America/Menominee, Pacific/Pago_Pago, Pacific/Guam.  

Worldwide there are 193 zones: the naming scheme is "continent-or-ocean/largest-city", with "continent-or-ocean/political-subdivision/largest-city" used when "largest-city" alone is ambiguous.  Worldwide there are 134 DST rulesets with mnemonic names.

**Comment by johnwcowan** [comment]
No, there isn't.  But it would be easy to write a script to convert the standard format (which is a text file) into RDF.  If you like, I'll put together a script (probably in bash and/or awk) to do just that.
