### ISSUE TITLE
Should `gist` describe its preferred prefix and namespace URI using VANN?

### ISSUE THREAD

**Issue by pmcb55** [semanticarts/gist#684]
It's become very common practice in more recent years for ontologies to explicitly provide simple metadata for their **_preferred_** prefix and namespace URI using the long-standing, and stable, [VANN vocabulary](http://purl.org/vocab/vann/).

For gist, this would simply be including the following two new VANN triples:
```
prefix vann: <http://purl.org/vocab/vann/>

<https://ontologies.semanticarts.com/o/gistCore> a owl:Ontology;
    vann:preferredNamespacePrefix "gist" ;
    vann:preferredNamespaceUri "https://ontologies.semanticarts.com/gist/" .
```

**Note**: In the case of the prefix, this is just potentially helpful extra metadata - i.e., by explicitly stating a _preferred_ value it can help maintain a higher degree of consistency among people using that ontology.

**Note**: In the case of the namespace URI, this can be helpful in linking the ontology resource (i.e., `<https://ontologies.semanticarts.com/o/gistCore>` in the case of gist) back to the actual namespace URI it describes (i.e., `"https://ontologies.semanticarts.com/gist/"`).

**Note**: The `rdfs:range` of the VANN `preferredNamespaceUri` predicate (although not explicitly stated in the VANN documentation) is accepted to be an `xsd:string`, and not an IRI, or `xsd:anyURI`.
I think this is deliberate to allow processors perform simple string manipulation on the IRIs of terms from a vocabulary, but also because to-date the notion of a Namespace has not been explicitly denoted (i.e., there are no `rdf:Namespace` or `owl:Namespace` types, and no associated `rdf:namespace` or `owl:hasNamespace` predicates), and so dereferencing a Namespace URI in-and-of-itself has generally (but not always!) been expected to return the description of that ontology - but that description has never been expected to contain triples describing the Namespace itself (whether it **_should or not_** is a separate issue :) !).

**Comment by uscholdm** [comment]
This makes a lot of sense to me, especially this:

>  In the case of the namespace URI, this can be helpful in linking the ontology resource (i.e., `<https://ontologies.semanticarts.com/o/gistCore>` in the case of gist) back to the actual namespace URI it describes (i.e., `"https://ontologies.semanticarts.com/gist/"`).

**Comment by rjyounes** [comment]
We consulted the VANN ontology and determined that these are not appropriate.

1. They are specifically for use in an XML document (from VANN ontology).
2. We don't like the use of "Uri" rather than "Iri."
3. The URI is a string.
4. What is the purpose? Preferred namespace is already defined from the namespace. Prefix is obvious from usage in the ontology.

**Comment by rjyounes** [comment]
@Jamie-SA Where did we leave this? Were you going to do any additional exploration, or is it still under group review?

**Comment by Jamie-SA** [comment]
Here are the SHACL term definitions for everyone to review:
```
sh:PrefixDeclaration
	a rdfs:Class ;
	rdfs:label "Prefix declaration"@en ;
	rdfs:comment "The class of prefix declarations, consisting of pairs of a prefix with a namespace."@en ;
	rdfs:subClassOf rdfs:Resource ;
	rdfs:isDefinedBy sh: .

sh:declare
	a rdf:Property ;
	rdfs:label "declare"@en ;
	rdfs:comment "Links a resource with its namespace prefix declarations."@en ;
	rdfs:domain owl:Ontology ;
	rdfs:range sh:PrefixDeclaration ;
	rdfs:isDefinedBy sh: .

sh:prefix
	a rdf:Property ;
	rdfs:label "prefix"@en ;
	rdfs:comment "The prefix of a prefix declaration."@en ;
	rdfs:domain sh:PrefixDeclaration ;
	rdfs:range xsd:string ;
	rdfs:isDefinedBy sh: .

sh:namespace
	a rdf:Property ;
	rdfs:label "namespace"@en ;
	rdfs:comment "The namespace associated with a prefix in a prefix declaration."@en ;
	rdfs:domain sh:PrefixDeclaration ;
	rdfs:range xsd:anyURI ;
	rdfs:isDefinedBy sh: .
```

Here is their example of how to use them.
```
sh:
	a owl:Ontology ;
	rdfs:label "W3C Shapes Constraint Language (SHACL) Vocabulary"@en ;
	rdfs:comment "This vocabulary defines terms used in SHACL, the W3C Shapes Constraint Language."@en ;
	sh:declare [
		sh:prefix "sh" ;
		sh:namespace "http://www.w3.org/ns/shacl#" ;
	] .
```

**Comment by rjyounes** [comment]
Michael/Rebecca: The SHACL terms aren't precisely what we want to express - they're used to associate a prefix with a namespace, not to specify the namespace itself. Could mint our own annotation properties.

Dan: Could use the SHACL mechanism to specify multiple prefixes; e.g., the tbox, abox, and cbox patterns.

Jamie: This way applications like visualizations could use the prefix declarations to match an IRI and display the prefix rather than the full namespace.

Dan: Could put the SHACL prefix declarations into a separate file. This provides the guidance for applications without adding application-level cues to the ontology.

Can add a bare PrefixDeclaration object in a separate file, without linking to the ontology

With a blank node:
```
[] a sh:PrefixDeclaration ;
	sh:prefix "gist" ;
	sh:namespace "https://ontologies.semanticarts.com/gist/" ;
	.
```
With an IRI node:
```
gist:_PrefixDeclaration_gist a sh:PrefixDeclaration ;
	sh:prefix "gist" ;
	sh:namespace "https://ontologies.semanticarts.com/gist/" ;
	.
```


On gist:

```
<https://ontologies.semanticarts.com/o/gistCore>
	a owl:Ontology ;
	owl:versionIRI <https://ontologies.semanticarts.com/o/gistCore11.0.0> ;
	skos:definition "gist is a minimalist upper ontology created by Semantic Arts."^^xsd:string ;
	skos:prefLabel "gist"^^xsd:string ;
	gist:license "https://creativecommons.org/licenses/by-sa/3.0/"^^xsd:string ;
	sh:declare [
                a sh:PrefixDeclaration ;
		sh:prefix "gist" ;
		sh:namespace "https://ontologies.semanticarts.com/gist/" ;
	]  ;
	.
```
Options:
- Do nothing
- Mint our own annotations
- Use the SHACL prefix declarations on the ontology
- Put the SHACL prefix declarations in a separate file

What about the output of tarql?  - Can add prefix declaration blank nodes as above if desired.

Which prefixes would you declare? 
- Minimally, the tbox/cbox/abox prefixes - e.g., pleo, pleox, pleod
- Probably not standard prefixes like owl, rdf, rdfs, skos, xsd (these are generally built into applications anyway). Could put into a separate file.

PROPOSAL:

```
<https://ontologies.semanticarts.com/o/gistCore>
	a owl:Ontology ;
	owl:versionIRI <https://ontologies.semanticarts.com/o/gistCore11.0.0> ;
	skos:definition "gist is a minimalist upper ontology created by Semantic Arts."^^xsd:string ;
	skos:prefLabel "gist"^^xsd:string ;
	gist:license "https://creativecommons.org/licenses/by-sa/3.0/"^^xsd:string ;
	sh:declare gist:_PrefixDeclaration_gist ;
	.

gist:_PrefixDeclaration_gist a sh:PrefixDeclaration ;
	sh:prefix "gist" ;
	sh:namespace "https://ontologies.semanticarts.com/gist/" ;
	.
```

Add standard prefixes `skos`, `owl`, `rdf`, `rdfs`, `xsd` to a separate file. These could be imported into gist. Don't use blank nodes.

**Comment by pmcb55** [comment]
Just catching up on this issue now(!), and I totally agree with the decision you folks arrived on here!

But shouldn't the object of the `sh:namespace` triple you give in your example for gist be explicitly datatyped as `xsd:anyURI`, as per the [SHACL spec](https://www.w3.org/TR/shacl/#sparql-prefixes) itself (i.e., "**_The values of `sh:namespace` are literals of datatype `xsd:anyURI`_**")...?

**Comment by Jamie-SA** [comment]
Hi @pmcb55, it probably should be. Interestingly, even the developers of SHACL made the same mistake in their original ontology... Also interesting that it was corrected 2 years ago by @pwin, why weren't you on the call that day Peter? :)

**Comment by rjyounes** [comment]
This was completed and released.
