### ISSUE TITLE
Should we have multiple numerators and denominators for RatioUnits?

### ISSUE THREAD

**Issue by uscholdm** [semanticarts/gist#69]
In a prior internal (not really a) release of gist9.0.0 and other prior versions, RatioUnit has exactly 1 UnitOfMeasure as a numerator and exactly one as a denominator. Now it can have more than one. 
I cannot work out what that means.  How might that ever be useful?

**Comment by tedhills** [comment]
I raised this as an issue in email and Gist Council discusssions perhaps a year ago. I am happy that it can now be a GitHub issue. I am also happy to see that my request has been granted in gist 9.

I've attached an in-depth paper that explains the particular problem I encountered. Short summary: if there's more than one way to calculate something, gist would force you to choose just one. Since the SI defines more than one way to calculate energy, and in the world at large there is no restriction in general on how many ways something may be calculated, my position was that these restrictions were getting in the way of representing the world as it really is.
[ProposedChangesToProductUnitAndRatioUnit.docx](https://github.com/semanticarts/gist/files/3962897/ProposedChangesToProductUnitAndRatioUnit.docx)

**Comment by rjyounes** [comment]
Currently a RatioUnit is allowed to have more than one numerator and denominator. Is that useful?

**Comment by daliadahleh** [comment]
Having multiple derivations for a unit does require RatioUnit to allow for multiple numerators and denominators, and for ProductUnit to allow for multiple multipliers and multiplicands. We'll keep this restriction removed.

However, the particular unit subclasses should have cardinality restrictions. For example, AreaUnit should have 'exactly 1' multiplier and 'exactly 1' multiplicand, rather than 'some' of each.

Also, unit subclasses should be disjoint (ie. AreaUnit disjoint with TemperatureUnit, etc) to avoid incorrect inferences.

**Comment by uscholdm** [comment]
> Having multiple derivations for a unit does require RatioUnit to allow for multiple numerators and denominators

What is a simple example of this?

**Comment by uscholdm** [comment]
> However, the particular unit subclasses should have cardinality restrictions. For example, AreaUnit should have 'exactly 1' multiplier and 'exactly 1' multiplicand, rather than 'some' of each.

An AreaUnit IS a ProductUnit which says you CAN have multiple multiplicands and multipliers.  Seeming contradiction here.

**Comment by uscholdm** [comment]
> Also, unit subclasses should be disjoint (ie. AreaUnit disjoint with TemperatureUnit, etc) to avoid incorrect inferences.

I agree

**Comment by daliadahleh** [comment]
> What is a simple example of this?

From Ted's example for Energy, which can be derived as either 'Force x Distance' or 'Power x Time'.

We would define EnergyUnit as having:

( (Multiplier 'exactly 1' ForceUnit) and (Multiplicand 'exactly 1' DistanceUnit) )
or
( (Multiplier 'exactly 1' PowerUnit) and (Multiplicand 'exactly 1' TimeUnit) )

**Comment by uscholdm** [comment]
This is still in TBox-land.  Consider an actual instance of an energy unit, say  'newton'.  It's ambiguous if we say it can have two multiplicands and two multipliers because you might get them mixed up and think a Newton can be Force x Time or Distance x Power.  I think this example points to a deeper problem with how gist does ratio and product units.   

However, on the principle of erring on under- rather than over-constraining, I'm fine with leaving the restrictions as they are and leaving it up to people's common sense and physical knowledge to not screw things up.
