### ISSUE TITLE
Add gist:_year and Maybe gist:_month, gist:_hour, gist:_second (but as a gist:DurationUnit)

### ISSUE THREAD

**Issue by dhurlburtusa** [semanticarts/gist#704]
I needed `gist:_year` in a recent project, but it doesn't exist. Only `gist:_day`, `gist:_minute`, and `gist:_millisecond` exist.

Note: `gist:_second` exists but it is not a `gist:DurationUnit` but a `gist:BaseUnit`. Maybe it should be renamed to `gist:_base_unit_second` so that `gist:_second` can be used for `gist:DurationUnit`. Other gist:BaseUnits should be updated to following whatever naming convention is used for gist:BaseUnits.

I defined it as follows (used a different prefix in the project):

```turtle
gist:_year
	a
		owl:NamedIndividual ,
		gist:DurationUnit
		;
	skos:definition "A duration unit that is 365.256 days long."^^xsd:string ;
	skos:prefLabel "year"^^xsd:string ;
	# Based on the number of ephemeris days for the J2000.0 epoch in a [sidereal
	# year](https://en.wikipedia.org/wiki/Sidereal_year) rounded to 3 decimal
	# points.
	# 365.256 * 86400 = 31,558,118.4
	gist:conversionFactor "31558118.4"^^xsd:double ;
	gist:hasBaseUnit gist:_second ;
	gist:unitSymbol "yr"^^xsd:string ;
	.
```

Consider adding `gist:_month` and `gist:_hour` as `gist:Duration` units too.

**Comment by uscholdm** [comment]
First, gist:_second is inferred to be a DurationUnit, so we are good there.

The day, minute and millisecond units were only needed for precision for TimeInstant which is not gone. So they are no longer needed in gist. They are not used any more. 

There is a separate issue for whether we want to include certain units beyond the base units. If we have day, millisecond and hour, where do we stop?  Fortnight? Week?   We are planning to have some sample units of this sort in a separate file.

Month is a problem, since months vary in length. 

PROPOSAL:
- don't include any non-base units in gistCore
- have a separate file for commonly used units across multiple enterprises, say the duration units ,as well as maybe speed, area, acceleration etc.
- Have a larger file for any number of other less generic units from specific fields and industries. This file could import the other one.

ALSO:
- I think this is already mentioned in another issue.

**Comment by dhurlburtusa** [comment]
> First, gist:_second is inferred to be a DurationUnit, so we are good there.

Ah, I ran the Hermit reasoner in Protege and now I see that it is inferred as a DurationUnit.

Is it because a DurationUnit has equivalent class of
```
gist:SimpleUnitOfMeasure and (gist:hasBaseUnit value gist:_second)
```
and `gist:_second` has `rdf:type` of `gist:BaseUnit` which is a subclass of `gist:SimpleUnitOfMeasure` and it also has `gist:hasBaseUnit` of `gist:_second`?

**Comment by uscholdm** [comment]
Yes, that is why. You can verify that using the explain button in Protege.

**Comment by dhurlburtusa** [comment]
> You can verify that using the explain button in Protege.

Thanks for pointing this out!

**Comment by uscholdm** [comment]
@dhurlburtusa 
This is subsumed by #697
