### ISSUE TITLE
Make ContentExpression a subclass of IntellectualProperty

### ISSUE THREAD

**Issue by rjyounes** [semanticarts/gist#718]
`ContentExpression` is currently a subclass of `Content`; however, the `skos:definition` reads:

Intellectual Property reduced to text, audio etc.  If it contains text (written or spoken), it may be in a language.

Based on this, it seems that it should also be a subclass of `IntellectualProperty`.

**Comment by uscholdm** [comment]
@rjyounes Maybe the text definition is wrong. Perhaps it should be:
- `"Content reduced to text, audio etc.  If it contains text (written or spoken), it may be in a language."`
rather than
- `"Intellectual property reduced to text, audio etc.  If it contains text (written or spoken), it may be in a language."`

**Comment by rjyounes** [comment]
Closing - this doesn't really make sense. Not all expressed content is intellectual property.
