### ISSUE TITLE
Make gist documentation more accessible

### ISSUE THREAD

**Issue by rjyounes** [semanticarts/gist#727]
1. Add link to gist-docs repo on the gist repo readme
2. Add link to widoco page to gist repo and gist-docs readme
3. gist-docs repo needs an index.html page with links

**Comment by Jamie-SA** [comment]
The Widoco page is program generated. Unless someone says otherwise I'm going to guess that the second bullet above is not part of the Widoco output.

Also, I think the gist README should have links to educational resources. I will add a PR for that here.

The 1st and 3rd bullet points above will need to be done in the gist-docs repo, not here.

**Comment by Jamie-SA** [comment]
I deleted my previous comment because I had misread the original request.

1. I will be submitting a PR for this
2. The Widoco page is program generated. Unless someone says otherwise I'm going to guess that this is not a normal part of the Widoco output.
3. This will need to be done in the gist-docs repo, not here. I will create an issue for it over there.
