### ISSUE TITLE
Remove properties hasSubTask and hasDirectSubTask

### ISSUE THREAD

**Issue by rjyounes** [semanticarts/gist#733]
This is covered by `hasPart` and `hasDirectPart` and object `Task`.

**Comment by rjyounes** [comment]
Dave defined these predicates as an initial effort to distinguish various part-of relationships. We agree as a group to remove these predicates, but will run it by Dave first. The part-of issue is larger, and needs to be tackled as a separate topic.

**Comment by hmoore-sa** [comment]
I was a little delayed in getting started on this due to client work, but I have an email out to Dave and will move ahead based on his feedback. WIP.

**Comment by mkumba** [comment]
Yeah I guess its ok to remove hasSubTask and replace it with isDirectPartOf

As I think of it, what we really need is a way to distinguish the part of relationship that must be exclusive and therefore is a candidate for cascading delete.  My current thinking is it is the difference between a physical part and a digital part.  A physical part (with a serial number say) can only be directly part of one other physical part (a Vin number say), and if the vin number is destroyed so is the part.  But the design of that part (caburettor) could be part of many higher level designs (car, truck etc) and is not deleted when its parent is deleted. 

On the task side a subtask is exclusive like that (I think ) but a template task isn't, we could share a template task across many template projects.  

So now we need a name for this distinction.

**Comment by rjyounes** [comment]
Our thinking here is that we need to think through the complexities of mereology and implement it in a consistent way. Until we do that, it doesn't make much sense to differentiate one.

**Comment by mkumba** [comment]
Ugghhh that feels like an infinite regress.  I just went back and sped re-read Peter Simons Parts and in the 300+ pages there are one or two pretty good ideas.  (Its pretty old (1987) and predates DL and OWL and everything but I get the sense the world has not moved on, that the quote on the cover came to pass “Parts could easily be the standard book on mereology for the next twenty or thirty years”)

Ok

Let’s sort it into things we can deal with.

1) Real physical countable things (PhysicallyIdentifialItems).  With the exception of his hi-way example (two roads share an intersection) pretty much nothing else physical shares physical parts.  Systems share parts.  But systems aren’t PIIs. And the hi ways are probably better thought of as networks, not PIIs.
2) Real Physical Substance (mass nouns) Two beers share alcohol, but it isn’t the same alcohol, it’s the same type of alcohol.
3) Physical Items can contain substance (my car might contain some fuel)
4) Temporal things (events) can have temporal parts.  The play last night had three acts.
5) Digital things can share parts because of the non exclusivity of digital things.  Two anthologies can contain the same poem.
6) There can be temporal part of.  The tires on my car this year are not the same as last year.
7) The ship of Thesis is just a point of view.  Do you believe a) the functional whole (the original ship) is the whole, or b) the sum of the original parts.  I’m going with  a), but really you just have to pick one.  Rarely comes up.  The closest we get to it is systems and networks, where it is quite obvious the system or the network is the persistent whole, no matter what pipes, or routers or whatever you swap in and out.
8) How do we want to deal with groups or sets.  Is a subset a part of the bigger set?
9) Broad question: is the whole greater than the sum of its parts?  Answer: yes in almost all cases that we care about.  A pile of airplane parts is not greater than the pile of airplane parts if it’s just sitting in a warehouse.  If you make a flyable airplane out if it is is.  Same parts, different whole.
10) should we use the same predicate to say that a department is part of a division as we do to say this serialized jet engine is part of that tail number plane.

If there was anything useful in mereology that I missed in the above, (other than proper parts, and arguments about whether a whole is part of itself, and a lot of math that was mostly self referential) let me know and we can add it in

PS this is reasonably good
<https://www.w3.org/2001/sw/BestPractices/OEP/SimplePartWhole/>
Simple part-whole relations in OWL Ontologies<https://www.w3.org/2001/sw/BestPractices/OEP/SimplePartWhole/>
w3.org<https://www.w3.org/2001/sw/BestPractices/OEP/SimplePartWhole/>
[favicon.ico]<https://www.w3.org/2001/sw/BestPractices/OEP/SimplePartWhole/>
Especially Pattern 4: don’t confuse parts and kinds






On Apr 16, 2023, at 3:24 PM, Rebecca Younes ***@***.***> wrote:



Our thinking here is that we need to think through the complexities of mereology and implement it in a consistent way. Until we do that, it doesn't make much sense to differentiate one.

**Comment by uscholdm** [comment]
> A physical part (with a serial number say) can only be directly part of one other physical part (a Vin number say), and if the vin number is destroyed so is the part.

This does not seem right.  A physical part can't be part of more than one thing **at the same time**, but I can swap engines with another car. Neither engine was destroyed.

**Comment by rjyounes** [comment]
> This does not seem right. A physical part can't be part of more than one thing at the same time, but I can swap engines with another car. Neither engine was destroyed.

I think you'd have to say in this case that you first remove the engine from the first VIN number, at which point it is no longer part of it, then destroy the VIN number, then put the engine in the second car. At no time is the part part of more than one thing, and when the VIN number is destroyed the engine was no longer part of it.

**Comment by uscholdm** [comment]
> you first remove the engine from the first VIN number, at which point it is no longer part of it, then destroy the VIN number

No, the VIN number is attached to the chassis - it still exists.

**Comment by mkumba** [comment]
The VIN number represents the chasis, and therefore the core of the car.  If you destroy the car while engine A is in it, then engine A is gone.  If you wait until someone takes out engine A and puts in engine B and then the car goes up in a big fireball, engine B is gone, but engine A lives on.

With physical things there are (vanishingly few) cases where a physical thing is legitimately and temporally part of two different physical items.

However this happens all the time with digital parts, which I think is why people get confused.

The 1,588 cc (1.6 L) B-Series DOHC I4 engine was “part of” a half dozen MG models and several hundred thousand actual MGs, but no one engine was actually every simultaneously in two cars.

In fact you could pretty legitimately go the other way, and say that direct part of was functional: if an engine was directly part of two cars, they must be the same car.

On Apr 21, 2023, at 2:49 PM, Michael Uschold ***@***.***> wrote:



you first remove the engine from the first VIN number, at which point it is no longer part of it, then destroy the VIN number

No, the VIN number is attached to the chassis - it still exists.

**Comment by hmoore-sa** [comment]
Hi all,

Thanks for all the comments on the larger issue! After talking to Rebecca this morning, I've submitted the removal PR for gist:hasSubTask and gist:hasDirectSubTask. Sounds like there is wider discussion to be had- let me know if we need to open another issue for it.

Thanks,
Heather
