### ISSUE TITLE
Units of Measure should have a hasStandardUnit restriction. 

### ISSUE THREAD

**Issue by uscholdm** [semanticarts/gist#75]
Every UnitOfMeasure has a standard unit which may or may not be a base unit. There should be a restriction saying so.

**Comment by rjyounes** [comment]
Standard unit = coherent unit.

Base is a subclass of Standard.

Dave: Historically, they were separated because of modularity - if you didn't want coherent units you didn't need to take all this other stuff. 

Peter: it's contextual. 

Conclusion: These are valid, but we will not add the restrictions.
