### ISSUE TITLE
gist:SchemaMetaData can have a formal definition

### ISSUE THREAD

**Issue by justin2004** [semanticarts/gist#772]
If I were to look for instances of `gist:SchemaMetaData` _in use_ without using that URI I would write a query like:

```sparql
select * where {
:schemametadata0 a gist:Content .
:spec0 a gist:Specification .
:spec0 gist:isExpressedIn|^gist:isAbout|gist:isRenderedOn :schemametadata0 .
:data0 gist:conformsTo :spec0 .
:data0 a gist:Content .
} 
```

And in gisty english: Schema Meta Data is Content that expresses a Specification and some other Content conforms to that specification.

I think we can turn that into a formal definition, right?

**Comment by uscholdm** [comment]
That is an interesting stab at defining SchemaMetadata, and captures some important meaning. One subclass of SchemaMetadata is Column, as in a RDB table.  It's not obviously necessarily true that the column, middleName is a specification that some content conforms to.  Its a stretch to suppose that everythign we might conceive as SchemaMetaData would have to conform to this definition.  I see this class as being a bit like Intention, very abstract, not intended (so to speak) to be formally definable and used mostly as a topical grouping of classes that are similar in some intuitively graspable way.

**Comment by justin2004** [comment]
> It's not obviously necessarily true that the column, middleName is a specification that some content conforms to.

Sure it is. If you look at the DDL for a table definition you'll see a column is a specification for the kind of values it can take.

**Comment by uscholdm** [comment]
PROPOSAL: close this issue w/o doing anything.

Two main reasons.
1. I am not convinced that everything we think of as `SchemaMetaData` would conform to the proposed definition.  `SchemaMetaData` is a bit like Intention, very abstract, not intended to be formally definable and used mostly as a topical grouping of classes.
2. Even if it was, it is not clearly useful to have the definition.
3. As stated the definition cannot be expressed in OWL because it requires a rule that two variables are different from one another.
