### ISSUE TITLE
Rename serialize script

### ISSUE THREAD

**Issue by rjyounes** [semanticarts/gist#86]
To serialize is, roughly, to convert an object to a text document, not to reformat one text document as another text document. A more accurate name would be "format," or "reserialize."

**Comment by uscholdm** [comment]
This is historical. There was an effort to have a standard way to serialize an ontology, so the project had ‘serialize’ in its name.  Turns out its main use is to convert any potentially non-standard- serialization to a standard one, so technically you are correct, it is a translation, or re-fromatting.   It Is not doing serailzation per se.

I recommend this is a small enough issue to ignore.

M.

**Comment by rjyounes** [comment]
Reference to the script in bundle.bat also needs to be changed.

**Comment by rjyounes** [comment]
Too nitpicky even for me.
