### ISSUE TITLE
Add to gistMediaTypes.ttl

### ISSUE THREAD

**Issue by stevenchalem** [semanticarts/gist#900]
I would  like to discuss how to best handle media types not currently covered in gistMediaTypes.ttl. I'm working on a project that will require a lot of media types not currently covered. The project involves cataloging most of the files on our SA sharepoint drive, so any media types appearing there will need to be covered.

If we add all the new media types to gistMediaTypes.ttl, what patterns should we follow? Or should we consider the alternative of using the IANA media type namespace?

https://www.w3.org/ns/iana/media-types/

**Comment by Jamie-SA** [comment]
I had a plan to some day write a script to create a new Media Type file with all of the defined media types from IANA (and leave the smaller file available for anyone that doesn't want to import all MediaTypes).

When I proposed the creation and format of the gistMediaTypes file I had not found the link you provided. I might have suggested using those IRIs if I had known about them.

However, if you look at their "RDF" it is not very good. And they make the common mistake of creating classes for each Media Type whereas our file creates instances of a `gist:Category` (this is more in line with our recommendations and how gist does things).

For instance:
```
gist:FormattedContent
        a owl:Class ;
        owl:equivalentClass [
                a owl:Class ;
                owl:intersectionOf (
                        gist:ContentExpression
                        [
                                a owl:Restriction ;
                                owl:onProperty gist:isExpressedIn ;
                                owl:someValuesFrom gist:MediaType ;
                        ]
                ) ;
        ] ;
        skos:definition "Content which is in a particular format. (E.g., HTML, PDF, JPG.)"^^xsd:string ;
        skos:prefLabel "Formatted Content"^^xsd:string ;
```

Here we are using gist:MediaType to "tag" a node representing some `FormattedContent` with a Media Type, instead of saying that the node itself "is" an instance of a `gist:MediaType`.

**Comment by rjyounes** [comment]
Jamie: IANA defines media types as classes, we define them as instances.

Rebecca: Adding triple to the IANA IRIs results in namespace squatting and, if a user ingests both, punning.

Someone should look at the IANA ontology and RDF to compare to ours and report back.

**Comment by rjyounes** [comment]
I would like to add `application/pdf` and `application/msword`.

**Comment by rjyounes** [comment]
Closing now. The immediate use case no longer exists. This may arise in the future because the dev team needs additional media types.
