### ISSUE TITLE
Have Q/A tool to run before the release process

### ISSUE THREAD

**Issue by uscholdm** [semanticarts/gist#987]
This is based on a discussion in #297. The idea is to have a Q/A tool that can be run during regular development rather than waiting to be caught during the release process.

We may already be doing this on each commit, in which case we can close this issue.

**Comment by rjyounes** [comment]
Closing per preceding comment.

**Comment by uscholdm** [comment]
@rjyounes I'm confused. If this is already being done, why did you recommend (in #297) to create #988 ?

**Comment by rjyounes** [comment]
I'm also confused. The title of the issue says "before the release process," whereas the description says "The idea is to have a Q/A tool that can be run during regular development rather than waiting to be caught during the release process." Apparently you mean the latter?

Can you be specific about what Q/A tools you are thinking of? I also thought it would be a good idea to run some in the pre-commit hook, but we decided that, for example, the SHACL ontology validation would be too costly to run before each commit.

**Comment by uscholdm** [comment]
> I'm also confused. The title of the issue says "before the release process," whereas the description says "The idea is to have a Q/A tool that can be run during regular development rather than waiting to be caught during the release process." Apparently you mean the latter?
> 
> Can you be specific about what Q/A tools you are thinking of? I also thought it would be a good idea to run some in the pre-commit hook, but we decided that, for example, the SHACL ontology validation would be too costly to run before each commit.

Never mind, we are doing a lot of Q/A on each commit.  This shall remain closed.
